### ISSUE TITLE
Respons buttons (ty gl + kick)

### ISSUE THREAD

**Issue by klipson3** [Exslims/MercuryTrade#101]
Pls add this function. I want say "ty gl" and kick player one button. ty

**Comment by Exslims** [comment]
TOS violation, sorry

**Comment by RiboRino** [comment]
POE Trades Companion does this tho....

**Comment by Exslims** [comment]
yes, but this is illegal, and from the beginning the mercury is made with only the permitted functionality

**Comment by RiboRino** [comment]
Except Trade Companion has been around for 9 months and has 24 pages on the PoE forums. The developer follows the TOS.

**Comment by Exslims** [comment]
you have no idea how much shit was raised when I entered this feature in 1.0.0.1 (or 1.0.0.2), repeat I don't want.

**Comment by RiboRino** [comment]
Then there's no reason to use mercury trade over trade companion. It's inefficient.

**Comment by Exslims** [comment]
well, I'm not forcing anyone to use my program? if 1 click for you is a terrible problem

**Comment by FK1985** [comment]
Is it possible to bind keys directly without a text interaction?
For example "F4" ?

**Comment by klipson3** [comment]
thanks for the answer
