### ISSUE TITLE
Toggle options in settings not visible

### ISSUE THREAD

**Issue by lukasani94** [Exslims/MercuryTrade#105]
Example picture: http://i.imgur.com/DePNsaF.png

**Comment by Exslims** [comment]
Oo okay

**Comment by Exslims** [comment]
whats is your OS?

**Comment by lukasani94** [comment]
Windows 7 64 bit (with disabled Aero)
Java 64 bit

**Comment by Exslims** [comment]
in overseer component settings also there does not appear? (just create icon)

**Comment by lukasani94** [comment]
Yes, they are also not visible there.
Another minor unrelated bug/issue: if the chat editbox is open, MercuryTrade won't send automatically generated sale messages

**Comment by Exslims** [comment]
its not bug, it is simply not possible to check(in legal way) opened chat or not)

**Comment by lukasani94** [comment]
Ah ok. Any idea about the missing option icons? If it helps, I can do some troubleshooting (if you think you know what may be causing it?)

**Comment by Exslims** [comment]
you cant set up icon on overseer component?

**Comment by lukasani94** [comment]
I did, the option icons aren't there either. 
Here: http://i.imgur.com/onGaOYm.png

**Comment by Exslims** [comment]
ah you mean checkboxes?

**Comment by lukasani94** [comment]
yep. they're nowhere to be found for me, anywhere in the GUI. icons and stuff works

**Comment by Exslims** [comment]
i really don't know what is the reason, or rather I can set the old design these icons in the next version and that should help

**Comment by lukasani94** [comment]
I have found the problem.
In my Windows 7 configuration, I have Aero disabled (the taskbar/windows transparency). Therefore, "Themes" and "Desktop Windows Manager" services are disabled.
To test, I re-enabled Aero (and thus re-enabled "Themes" and "Desktop Windows Manager" services), the checkboxes are now visible. It seems like MercuryTrade relies on the Windows theme to create the checkboxes? Perhaps this functionality can be changed (maybe reverting to the old design, but I did not use MercuryTrade then, so I don't know if it works).

Aero enabled: http://i.imgur.com/WYOOeNW.png
Aero disabled: http://i.imgur.com/HRbZJRk.png

**Comment by Exslims** [comment]
yes, mercury use specific components design based on OS, but i can make the old design, which worked everywhere (i thought this too will work everywhere)

**Comment by lukasani94** [comment]
Ok, cool. Glad we figured it out :)

**Comment by Exslims** [comment]
fixed in 1.0.1.8+
