### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by vajura** [Exslims/MercuryTrade#106]
Hey man, love your app. 

The only thing that i am missing currently is a checkbox for messages "kick player from party". Because most of the time when you are done trading you just do "t4t" -> leave party, so a checkbox with a leave party + close panel option (which already exists) would be great

**Comment by Exslims** [comment]
you want t4t + kick from party as 1 click or t4t + close the panel? as for the first, I'm sorry but I can't do that because it violates the GGG's rules (I'd do it myself but i get a lot of problems because of this)
