### ISSUE TITLE
Taskbar "not responding"

### ISSUE THREAD

**Issue by AngryRoleplayer** [Exslims/MercuryTrade#108]
it's always like that. Is this normal?  When i hover over it it's "loading" icon and never responds. 
![snag-0002](https://user-images.githubusercontent.com/22470478/29306751-a82945f4-81a7-11e7-898e-96dfca5d5ea7.jpg)
Have windows 7 and latest java installed.

**Comment by Exslims** [comment]
provide app.log file from %userprofile%/appdata/local/mercurytrade folder pls

**Comment by AngryRoleplayer** [comment]
It was empty. It's weird but i went to the folder and started some local-updater.jar. Then nothing happened. Then i launched mercurytrade.jar as usual and now i see a taskbar and it works! ?

**Comment by Exslims** [comment]
really weird Oo

**Comment by AngryRoleplayer** [comment]
Yeah, cause i tried last week like 5 times it was all the same. Launches fine, i see tutorial tips. Lock the toolbar and then taskbar just "freezes" and "not responding". I will keep you updated if it will happen again

**Comment by Exslims** [comment]
k
