### ISSUE TITLE
Send message on party kick / party kick with message?

### ISSUE THREAD

**Issue by lukasani94** [Exslims/MercuryTrade#111]
Hi,

I'm wondering if you could add an option to send a custom goodbye message when kicking a person from your party after trade? Like: "thanks for trade and ss". That would reduce the amount of clicking required after trade, seems like a very intuitive change.

**Comment by Exslims** [comment]
seems like TOS violation [https://www.reddit.com/r/pathofexile/comments/5z0ivw/mercurytrade_update_now_open_source_stash/dev9soe/](https://www.reddit.com/r/pathofexile/comments/5z0ivw/mercurytrade_update_now_open_source_stash/dev9soe/)
