### ISSUE TITLE
Few issues with newest build. 1.0.1.8

### ISSUE THREAD

**Issue by Nipper4369** [Exslims/MercuryTrade#112]
The outgoing messages. There is no way to disable some features of it. and some times it spams the person. When I close the windows with the X it sends the thanks message. Not for sure but maybe some hidden buttons I was clicking not on it and it was spaming the person as well.

And the window that you mouse over to highlight items in stash tab.  It does not close when you close the main window out. I have to hit the little x with stash open to close it.

**Comment by Nipper4369** [comment]
some more. Not for sure how it happened but I was spammed and the window started moving up off my screen the more messages I got the farther it went up.

**Comment by Exslims** [comment]
1. about X button: I do not imagine how this could be, did you use hotkeys?
2. about stah tab panel: already fixed but you need to re-download mercury from release page.
3. now fix it

**Comment by Nipper4369** [comment]
1. I have no hotkeys set as far as I know.
2. K I will try that.
3. and yes I had it at the bottom of the page. But for each message that came in it keeped moving up the screen it self. and not staying at the bottom.

**Comment by Exslims** [comment]
all issues fixed in 1.0.1.8.1
