### ISSUE TITLE
Issue with latest release.

### ISSUE THREAD

**Issue by Xmitty** [Exslims/MercuryTrade#113]
Couple issues with the latest release.

I play on a 4K screen and scaling has always been a problem. Originally the 150% was barely enough, but now the scaling no longer works. With the latest update, it only scales the text / images in the notification box but the box itself does not scale. So, you get a bunch a scrunched up text that is unreadable. On normal scaling, it is too small to use on 4K.

http://imgur.com/a/EnIzN

Also, upward flow and downward flow seems to be broken now as well. As more messages come in, it moves the notification box up on the screen and closing out older messages doesn't move it back down. 

http://imgur.com/a/bd3L3

**Comment by Exslims** [comment]
all issues fixed in 1.0.1.8.1
closing out older messages doesn't move it back down. - so conceived, notification panel will snap into place when closed all the panels
