### ISSUE TITLE
[Request]More personalized message replys

### ISSUE THREAD

**Issue by Nipper4369** [Exslims/MercuryTrade#114]
I was wondering if there is a way to have a more personalized message to my replys

example. someone asks to buy a item via wispier messages via poe.trade or poeapp.

@%buyerName% Sorry! My %itemName% listed for %itemPrice% has already been sold.

or 

@%buyerName% Sorry! My %itemName% listed for %itemPrice% has already been sold.

**Comment by Exslims** [comment]
such requests torturing me for half the year, our view is that we are not willing to have a robotic message(coz they are confusing players), maybe the time will come and I'll do it but I do not see a pressing need, sorry.
