### ISSUE TITLE
Bug with 1.0.1.8.1 upwards flow.

### ISSUE THREAD

**Issue by Nipper4369** [Exslims/MercuryTrade#115]
With 4+ messages it still wants to flow downwards even with it set for upwards.

https://pastebin.com/2jBmdghM

the log might be long I will clean it up now so it will show only newer stuff for next time.

**Comment by Nipper4369** [comment]
http://prntscr.com/gawek2  screenshot of where I have it set

http://prntscr.com/gaweuk of what it looks like.

**Comment by Exslims** [comment]
it's a rather nasty functionality from the point of view of development and I was not included in the current version because I do not have time to finish, in the next version I will fix it.
btw thx for reports

**Comment by Exslims** [comment]
fixed in 1.0.1.9
