### ISSUE TITLE
FPS issues with new update.

### ISSUE THREAD

**Issue by SimpleKookie** [Exslims/MercuryTrade#116]
I got on PoE and updated through the app. Since I got the new app I got from about 150 FPS to about 50 FPS. Have to keep it closed.

**Comment by Nipper4369** [comment]
check your poe settings make sure vsync is not on.

**Comment by SimpleKookie** [comment]
My PoE settings are fine, I haven't touched them. If I have Mercury Trade on, I lose about 100 FPS. Exit it, all good.

**Comment by Redguin** [comment]
Same issue here - without Mercury trade on PoE main screen FPS stays at 110. As soon as I activate it FPS drops to 35-40. 
Tested with and without Vsync, with and without dynamic resolution and changing all settings to low, still the same issue. This was running the .jar - will now test with the rar file. Edit: Same issue - FPS dropped to 50-60 and then as soon as I switched zones hit 35-40 again.

**Comment by ghpzin** [comment]
Don't know if it helps but it is a problem with opacity overlay over poe window (found out by using opacity in ahk script), using mercurytrade overlay outside the window doesn't lower fps.

**Comment by Exslims** [comment]
I unfortunately can't help with the fact that drops fps because code that draws on screen is part of the framework(Java) and I can't seem to affect him
