### ISSUE TITLE
1.0.1.8.1 reply buttons do not scale properly at 150% scale

### ISSUE THREAD

**Issue by snwkill** [Exslims/MercuryTrade#117]
The buttons on the notification panel do not scale properly with the scaling of the text, did not have this issue on previous version. 

![image](https://user-images.githubusercontent.com/31193671/29499301-18f998d2-85dc-11e7-8ca7-9c3045ba0d5c.png)

**Comment by Exslims** [comment]
fixed in 1.0.1.9
