### ISSUE TITLE
[bug] Notification window glides up.

### ISSUE THREAD

**Issue by Nipper4369** [Exslims/MercuryTrade#119]
I reported this before but was never address about it.

How it reproduce it.
Get a pm and minimize it via down arrow. 
Get one or 2 whispers to buy something and close them.
and for each whisper while the first one is still minimized makes the notification climb. I am using upwards option as well.

picture

http://prntscr.com/gazisu
windows are locked to the bottom of the window.

app.log was empty. I cleared if a few hour ago.

**Comment by gbragg** [comment]
[app.txt](https://github.com/Exslims/MercuryTrade/files/1237602/app.txt)

I'm getting this as well, and it's making MercuryTrade borderline unusable. I've reverted to an older version in the meantime. Looking forward to the fix so I can enjoy the latest version of this great tool!

**Comment by Exslims** [comment]
fixed in 1.0.1.9
