### ISSUE TITLE
MercuryTrade blocks mouse button press from registering in Mumble

### ISSUE THREAD

**Issue by Razunter** [Exslims/MercuryTrade#122]
I'm using side mouse button as push-to-talk in [Mumble](http://mumble.sf.net/) and it doesn't work with MercuryTrade open since v1.0.1.8.1

Works in Discord though.
Windows 10 x64 Creators. JAR-version as admin.

Mumble v1.3 dev.

**Comment by Exslims** [comment]
with 1.0.1.9 issue still appear?

**Comment by Razunter** [comment]
Yep. It's probably issue with Mumble and how it handles mouse press, but it's still annoying.
With MercuryTrade open Mumble "binds" empty as PTT button when pressing Mouse 4 or Mouse 5, closing MT helps right away.

**Comment by Exslims** [comment]
well, I'll see what I can do but I can't promise something

**Comment by Razunter** [comment]
Looks like it's fixed now.
UPD: Nope.
