### ISSUE TITLE
MercuryTrade registers mouse clicks as binds for messages.

### ISSUE THREAD

**Issue by ClKhrom** [Exslims/MercuryTrade#124]
For outgoing messages, I created a thanks message, and wondered what the new button was, so I clicked it. Twice. Big mistake.
Basically, it sends the message every time I click, and for some reason, **cannot be deleted.**
I can't delete whatever buttons I add.

**Comment by sicu** [comment]
Just clicking it and pressing ESC to unbind works for me

**Comment by Exslims** [comment]
fixed in 1.0.1.9
