### ISSUE TITLE
Inc. notification panel gigantic and flow direction upwards is broken after update 1.0.1.8.1

### ISSUE THREAD

**Issue by Snizh-Fize** [Exslims/MercuryTrade#125]
My [incoming notification panel](http://i.imgur.com/nY0LD4D.jpg) doubled in size after the latest update. The response buttons have the same size, no matter how small the text is.

The flow direction of the incoming notification panel is also [reversed](http://i.imgur.com/goM4w32.jpg), this means that the oldest trade is moving and does not stay at the bottom, which is really confusing when you do multiple trades at the same time.
- closing the first trade makes the whole panel [floating.](http://i.imgur.com/8BiKuJL.jpg) [2nd screenshot](http://i.imgur.com/AkKfCs9.jpg)
- also happens when I [minimized](http://i.imgur.com/JbD7kvK.jpg) the trade window

Small bug found on the new outgoing notificaton: when you create new buttons, there are [squeezed](http://i.imgur.com/IAZ3qEJ.jpg) together. 

[Applog](https://pastebin.com/LPfdXBUG)

Edit: was the new style intended or is my MercuryTrade bugged? I looked at other post and it seems I'm the only one with the new style.

**Comment by Exslims** [comment]
fixed in 1.0.1.9
