### ISSUE TITLE
Text of Out. notification panel not correctly shown (1.0.1.9)

### ISSUE THREAD

**Issue by Snizh-Fize** [Exslims/MercuryTrade#132]
The [text of the item](http://i.imgur.com/n568fJ9.jpg) is not correctly show in the outgoing notification panel.

The "leave party button" on the outgoing notification panel does not work. (msg. in PoE: The target of this operation was not a party member)

Suggestion: is there a way to leave the party and go to your hideout with one button?

Edit: The bugged text does not happen with [every item](http://i.imgur.com/nHrBMq8.jpg). So far I only had the problem with the Remnant of Corruption. Maybe a bug with case sensitive?

**Comment by Nipper4369** [comment]
another example https://image.prntscr.com/image/ASM8yUg5THyMNRoEbskkWw.png

**Comment by Exslims** [comment]
1. just no icon and a NP writes the name of currency
2. set your nickname in settings for leave button

**Comment by boxer421** [comment]
Same bug with all new currencies from the league, you should add their icons to fix that.

**Comment by Exslims** [comment]
ye i know, in next update
