### ISSUE TITLE
[Feature Request] Tooltips on hotkey icons

### ISSUE THREAD

**Issue by Dgc2002** [Exslims/MercuryTrade#135]
Currently the Hotkey configuration menu looks like this:

![image](https://user-images.githubusercontent.com/3957791/29751747-416255c6-8b17-11e7-95ff-29ddd3bd451d.png)
  
  
I have no clue what a couple of these icons mean and that information isn't immediately available. I'd suggest either a tooltip or just the same text from the icon's tooltips elsewhere:

![image](https://user-images.githubusercontent.com/3957791/29751752-6c9a52ca-8b17-11e7-8b41-c85d2fa5a1d2.png)

**Comment by Exslims** [comment]
ok. thx
