### ISSUE TITLE
How on earth do I use this???

### ISSUE THREAD

**Issue by Vertigodown** [Exslims/MercuryTrade#136]
Downloaded all the files, but not sure what to do???

Is there a .exe file?

**Comment by Exslims** [comment]
MercuryTrade

Download and Install Java: https://java.com/download

Download MercuryTrade.jar: Latest release

ALTERNATIVE LAUNCHER: MercuryTrade.RAR: Latest release. Unpack and run the attached .exe as administrator! Try this launcher when something is not working.

I have a problem: Troubleshooting

Feedback and suggestions: Github Discord

**Comment by Exslims** [comment]
when you installed java just double click on MercuryTrade.jar

**Comment by Vertigodown** [comment]
Ty
