### ISSUE TITLE
Windows' taskbar on top of chrome when Mercury Trade is open

### ISSUE THREAD

**Issue by Vasllo** [Exslims/MercuryTrade#137]
I've tried to kill and restart the explorer.exe proccess and it didn't help. When I closed Mercury Trade, the taskbar went back to normal, and once I opened it again, it bugged again. This is not happening right now, so it doesn't happen always. This happens with my PoE aswell sometimes, but I never thought anything about it because but when it does, I usually fix it just by going to the desktop and coming back to the game.
My computer has Mercury Trade on the startup and today, I noticed there were two Java windows open and stuck (nothing would happen when I clicked on them), I closed Mercury Trade and they went away, opened MT again and the reported bug happened.

**Comment by Exslims** [comment]
Problem: Path of Exile constantly loses focus / Windows taskbar springs on top of the game while Mercury is running.

Fix: Disable Windows wallpaper slideshow.

**Comment by Vasllo** [comment]
I don't have it on, it's just a static wallpaper.

**Comment by Vasllo** [comment]
Issue still happening.

**Comment by Exslims** [comment]
if this happens without mercury then you need to look for a problem in another application, mb you are playing in fullscreen or some other "overlay" applications can cause this problem

**Comment by Vasllo** [comment]
As soon as I close Mercury Trade, it goes back to normal.
