### ISSUE TITLE
DX11 and "always on top" thing

### ISSUE THREAD

**Issue by kmeshavkin** [Exslims/MercuryTrade#138]
So I have a problem, where when I use MercuryTrade with DX11 in game, Mercury just do not work properly. Examples are: no notification message on trade, but sound still happens; when I press "save" button on "scale" window, nothing happens; quick key bind response do not work. But when I Alt Tab, suddenly everything works until next trade message, quick key use etc. Everything works perfect if PoE is minimized. Looks like Mercury is not getting enough privilage over PoE, but I run PoE from usual .exe (standalone) and I tried .exe version of Mercury and also tried running it with admin privilage.
One thing is if I switch to dx9ex, everything works perfectly fine.
Windows 7 x64, VSync is off (works bad with it even on dx9 - sometimes skips button presses or notifications)

**Comment by Exslims** [comment]
If alternative launcher did not help that I don't know how to fix it, could be the reason in another application
