### ISSUE TITLE
Notification panels not showing

### ISSUE THREAD

**Issue by Magoo76** [Exslims/MercuryTrade#139]
Hey

I reinstalled mercury trade for the 3.0 and ever since the notification panels are not showing up. I tried with and without admin, with 32 and 64 clients, With DX9 and DX11. But no changes. 

When I use the 'open tests' feature, panels are showing up, but only this way.

https://pastebin.com/SJjtcxX4 this is my app log

Thanks ! :)

**Comment by Exslims** [comment]
Problem: Notifications don't pop-up when receiving a trade messages.

Fix: Please make sure you've selected the correct Path of Exile folder.

if you delete MercuryTrade folder from %userprofile%/appdata/local, run poe client + run mercury, game path will be found automatically

**Comment by Magoo76** [comment]
thanks for the quick answer.

sadly I already tried to reselect path of exile folder. And I tried to delete MercuryTrade folder from %userprofile%/appdata/loca then run poe client + run mercury. 

But nothing has changed :/

I forgot to tell, mercury overseer is working perfectly. I have set 2 bars, one for anti bleed potion and one for anti freeze potion and works great.

**Comment by Exslims** [comment]
mb your client.txt in poe/logs folder readonly?

**Comment by Magoo76** [comment]
can't find client.txt but I didn't put anything related to POE in readonly.

I just renamed my POE folder into what it was originally. But nothing has changed.

**Comment by Exslims** [comment]
Client.txt located in Path of Exile/logs folder

**Comment by Exslims** [comment]
you renamed poe folder, so the path to the game was not right in MT, can you try again delete %userprofile%/appdata/local/MercuryTrade folder, run poe client -> run mercury

**Comment by Magoo76** [comment]
Thanks again for your time !

Client.txt wasn't in readonly. And yeah I renamed poe folder, but then I changed the path of MT. Im not that retard :p Still it doesn't work...

**Comment by Deadication** [comment]
I am having the exact same issue, i have completed all of the things you have requested and the problem persists, one temp fix i have found is turning the DnD button off and back on, hope that helps.

**Comment by krixalis** [comment]
Haven't looked at any of the source code of this project yet, I've installed Mercury for the first time today to try it out. Maybe it has to do with tabbing out and back in, like I thought in my original issue. Could have something to do with the DnD toggle @Deadication refers to.

**Comment by Exslims** [comment]
well, given that the trade monitor has been completely rewritten maybe somewhere I messed up, will try to find the issue

**Comment by Magoo76** [comment]
Your work around doesn't work for me @Deadication 

Don't know if it can help, but I have 2 screens, and I'm playing on windowed fullscreen.

**Comment by Exslims** [comment]
your OS?

**Comment by Magoo76** [comment]
wind10

**Comment by Exslims** [comment]
can you try 1.0.1.7 with old trade minitor and write if it will work?

**Comment by Magoo76** [comment]
trying out right now, will let you know in 2 min

**Comment by Magoo76** [comment]
not working either, should I delete the log MT folder before doing the test ?

**Comment by Exslims** [comment]
yes, try it

**Comment by Magoo76** [comment]
sorry forgot to tell you I tried, but still nothing has changed

**Comment by krixalis** [comment]
I just found out that if I have not yet switched out of the game and someone whispers me a trade request the notification does show up. I'm certain it has to do with the game losing/regaining focus.

**Comment by Exslims** [comment]
have you tried .exe as admin launcher?

**Comment by Magoo76** [comment]
Ok with 32 bits clients as admin, MT 1.0.1.7 and the folder deleted, seems to work :)

Trying with the latest release but I'm sure I already tried. will see

**Comment by Magoo76** [comment]
Well it is working with the latest MT now. With the poe client as admin. I was sure I tried it though. But I have redownload Mercury Trade so I don't know where the issue come from :/

But anyway, it's working now, thanks a lot for everything ! :)

**Comment by Magoo76** [comment]
Fuck, I was right when I said I already tried as admin with latest release. It seems I was using the wrong MT version when the panels were working. I don't know which one though. I thought I had download the latest :3 
But for now I'll use the 1.0.1.7 it's working great.

**Comment by Magoo76** [comment]
Ok, I'm sorry for the spam. But it seems it was my local\MercuryTrade which was corrupt or something. I deleted it one more time, ran MT (latest one), selected the poe's path then ran poe as admin. 

It's working now :D

**Comment by krixalis** [comment]
It's magically working for me now, too. So I have to take back what I said earlier, because I switched back in after making my previous comment, and the notification popped up from a trade whisper. No clue if it's gonna stay this way, what caused it or what caused it to stop messing up. I personally have not tried other versions and tried none of the solutions given in this thread.

**Comment by Magoo76** [comment]
mb I should make a new bug report, but now response buttons don't do anything when I click on them :3

**Comment by Magoo76** [comment]
Ok just had to put MT as admin aswell.

**Comment by TheOne320** [comment]
For me, the notifications also stopped showing. Deleting the config folder helped, but then the next day it stopped working again.

**Comment by Exslims** [comment]
provide app.log file from %userprofile%/appdata/local/MercuryTrade folder

**Comment by TheOne320** [comment]
app.log is completely empty.

**Comment by Saiasanc** [comment]
I am having the same issue ever since today's 1.0.2.0.2 update. I have tried both the .jar and .exe (as admin). I have tried deleting the %appdata%\Local\MercuryTrade folder and re-launching. Nothing helps. It just doesn't pop up the notifications at all anymore.  Oh and app.log is completely empty for me as well. So no abnormal errors or anything.

Edit: Confirmed. I just rolled back to 1.0.1.9 and everything is working perfectly again. So something in the latest update got borked good.

**Comment by Mallahet** [comment]
A temp fix I've found for the notifications not showing up in 1.0.2.0.2 is to click the Panel Unlock, move the notification panel a bit, and re-lock. Seems to work after doing that.

**Comment by elliotmendiola** [comment]
Leaving this comment here as my problem had a different solution but googling my problem lead here.  Sometimes after downloading the file in windows 10 it will have a checked option that disables it from reading and editing certain files in the system, this prevented it from detecting notifications on my computer.  Unchecking it fixed the issue

**Comment by zornfitzel** [comment]
https://github.com/Exslims/MercuryTrade/wiki/Troubleshooting

Problem: Buttons don't work (if you use poe trade macro)
Fix: Uncheck "Put tooltip results on clipboard" in the iteminfo tab in poe trade macro.

**Comment by WildestTM** [comment]
Hi everyone,

Don't know if anyone has tried this, but my installation of the game is an old one, been copying it over from one hard drive to another for years now and just updating.
I've had the same issue of Notification panel not showing up and after looking around in the source code i found my problem.

If you go into ur Path Of Exile installation folder and go to logs there is a Client.txt file that tracks everything chat related in the game and sometimes it can get to big for the program to actually read it properly. 
So just delete Client.txt when the game and Mercury Trade are both stopped and run them again.

This is what worked for me.

**Comment by ghost** [comment]
Currently getting this problem. It wont show up for either outgoing or incoming trade requests. I have tried deleting the \appdata\local\mercurytrade folder and running the program again, but have the same issue still. Tried downloading version before latest, that version does not work either.

Not sure how to fix. I play via steam, saw mention that that might be the issue but don't want to go to standalone launcher unless I have to. Log in that mercury trade folder was blank. (OS is windows 8)

Edit: sorry this was a total mistake on my end. All it took was updating Java (which i forgot to do previously)

**Comment by jacobsalzberg** [comment]
Same issue here.. it works for a while, then all of sudden it gets broken and I need to delete the userdata folder.
Never tried using the exe, not sure if it would fix.
