### ISSUE TITLE
Overseer import function?

### ISSUE THREAD

**Issue by Liquid5n0w** [Exslims/MercuryTrade#140]
Overseer is a great little addition, but I want to import an export from overseer, but it seems that isn't possible?  Or at least I can't find the import.

**Comment by Exslims** [comment]
new -> last button

**Comment by Liquid5n0w** [comment]
Wow, I missed it because it's off the bottom of the scroll, and I didn't expect it there, thanks!

**Comment by S1lverone** [comment]
It is strange to setup Overseer. I hope you will make it more User-friendly? All the best, happy to donate again
