### ISSUE TITLE
Overseer - Icon notifications not appearing

### ISSUE THREAD

**Issue by Morellenn** [Exslims/MercuryTrade#141]
Downloaded the latest release of MercuryTrade to use the Overseer part of it but for some reason the Icon overlays don't work. Capture seems to work fine but anything that requires an input/hotkey (Icon/Progressbar) doesn't seem to work. Downloaded and installed the rar and running the .exe as admin.

**Comment by Exslims** [comment]
what means "doesn't work", you created icon component with own hotkey, you press hotkey and icon doesn't appear?

**Comment by Exslims** [comment]
please provide app.log file from %userprofile%/appdata/local/MercuryTrade folder

**Comment by Morellenn** [comment]
> you press hotkey and icon doesn't appear?

Exactly that but it seems to be working now
I looked for the app.log file and it was empty so i decided to run it through the .jar file instead of .exe and it worked fine. Sorry for the waste of time!
