### ISSUE TITLE
Whispering trade offer on afk person closes notification window

### ISSUE THREAD

**Issue by AstroxV** [Exslims/MercuryTrade#142]
On 1.0.1.9.1, when whispering a offer from poe.trade to someone who is afk, opens the notification window for a short time, but as soon as the message comes the person is AFK, the message disappears. I'm not sure if this is intended, but if it is i would recommend making it an option to auto-close the notification when someone is afk.
I prefer to keep the notification open and make the decision to cancel the offer-notification myself if i find i have to wait too long. I
m not sure if this behavior was there with the last version too, as far as i remember the window stayed open at all times unless you closed it yourself.

**Comment by Exslims** [comment]
yes i will make it as option
