### ISSUE TITLE
'Leave party' button not working.

### ISSUE THREAD

**Issue by krixalis** [Exslims/MercuryTrade#145]
In outbound trade notifications, the 'leave party' button displays the in-game message "The target of this operation was not a party member".

**Comment by Exslims** [comment]
set-up your nickname in settings, coz we have only one way to kick yourself (/kick myCharacterNickname)

**Comment by krixalis** [comment]
Oh thanks, I overlooked that setting up. Expected PoE to have a /leave_party command.

**Comment by sAustinPower** [comment]
I know this is a really old thread, but I can't find anything else on this issue. Can anyone explain how to "set up your nickname in settings"? There's a field for "POE Accounts List", but adding a character name there doesn't do anything.
