### ISSUE TITLE
Notification panel, bar length not long enough, name always "..."

### ISSUE THREAD

**Issue by Gourdin** [Exslims/MercuryTrade#152]
Hi there,

Got a problem with my bar length with the last update, can't see people names in notification panel 

Exemple :
http://imgur.com/a/NT9xb

Can I manualy do something about that ? haven't found

Thanks and good job :)

**Comment by Exslims** [comment]
mouse over on right edge

**Comment by Gourdin** [comment]
I'm dumb... Thanks

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
