### ISSUE TITLE
Character name not appearing on notification panels

### ISSUE THREAD

**Issue by Astaroth368** [Exslims/MercuryTrade#155]
MercuryTrade Version: `1.0.1.9.0`

For the last few days character names have not been appearing on the notification panels making it difficult to tell who I'm responding to etc. Instead of the character name I just see `...` Even when I use the test notifications I see `...` instead of `Example1:`

The only thing I'm aware of changing before this started happening is enabling the `Show league` option. I have since disabled that option but it didn't resolve the problem.

![mercurytrade](https://user-images.githubusercontent.com/31566344/29995486-22eda4d6-8fe2-11e7-9895-6cf8b9ac4073.png)

**Comment by Exslims** [comment]
guys, please, it just window as classic Windows window, mouse over on right edge...

**Comment by Astaroth368** [comment]
I don't understand what you mean. I've moused over the entire window and can't see a name anywhere.

**Comment by Astaroth368** [comment]
ok, I get it now, you mean to resize the panel. Sorry didn't realise you could do that.
