### ISSUE TITLE
usernames in trade panels gone after recent update

### ISSUE THREAD

**Issue by mrooney** [Exslims/MercuryTrade#160]
![capture2](https://user-images.githubusercontent.com/123717/29997983-0b32f82e-8fe6-11e7-90a3-e15bc056e4e4.PNG)
Hello there, thanks for this fantastic tool! I noticed in a recent update in the last week or two, the username of the player is missing in trade notifications, so it makes it really hard to manage multiple trades at once as I don't know who wants/has what. Is this a user error or...something else? Currently I'm using 1.0.1.9.0.

**Comment by Exslims** [comment]
mouse over on right edge, just resise it

**Comment by mrooney** [comment]
🙇 THANK YOU 🙇 I had tried to find the resize edge previously and assumed there wasn't one.
