### ISSUE TITLE
Question or bug not for sure.

### ISSUE THREAD

**Issue by Nipper4369** [Exslims/MercuryTrade#168]
Is there a way when you hit ? to not show the .0 on the end of the currency? 

I have had some dumb people thinking I am trying to sell for more then what I have listed for.

Example.

Hit the ?
"Hi, are you still interested in Courtyard Map for 1.0 chisel?"

he thought I was trying to sell for 10 chisels.

**Comment by Exslims** [comment]
bug, will be fixed in next update
