### ISSUE TITLE
Option to disable whisper helper

### ISSUE THREAD

**Issue by OSwoboda** [Exslims/MercuryTrade#171]
I have no control about whisper messages... Ctrl as hotkey is really bad IMO, at least make it customizeable. And not being able to disable the function makes me not using MercuryTrade until this is added.

**Comment by Exslims** [comment]
look at notification settings page

**Comment by OSwoboda** [comment]
Patch server was down... that's why I there was no option to disable it. I downloaded it from github again and in the newest version the option is there. Your response wasn't helpfull at all...
