### ISSUE TITLE
Invite to party button BUG

### ISSUE THREAD

**Issue by devil81** [Exslims/MercuryTrade#173]
Heloo , 

For the last 3 hours 80% of the whispers i get from poe.trade with curency and items when i press invite button i get redirected to this guy : @Король_Жаб_Жаб 

so the x person request me 5c for 10alts and i press the invite button then i get the message " the party dont exist " and when i look to the interface i see this name to the pending invites - @Король_Жаб_Жаб 

To make the script working again i need to recive invite from someone and then script working fine for 2 - 3 min then it all over again ..

**Comment by Exslims** [comment]
try alternative launcher (run .exe as admin)
