### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by TimyTom** [Exslims/MercuryTrade#179]
I'm following exactly the steps written to install. Doesn't even start running.
PoE is in window mode.
1) MercuryTrade.jar
- I placed the file into \documents\My Games\Path of Exile
- Double clicking opens a folder with tons of sub folders and files in it. No .exe around here.

2) MercuryTrade.rar
- I placed the file into \documents\My Games\Path of Exile
- Double clicking doesn't do anything at all. It's not even right-clickable

What to do?
Please help
Thank you.
Tom

**Comment by Exslims** [comment]
Download and Install Java: https://java.com/download

**Comment by TimyTom** [comment]
Java is already downloaded and installed

**Comment by TimyTom** [comment]
Java Plug-in 11.144.2.01 x86
Using JRE version 1.8.0_144-b01 Java HotSpot(TM) Client VM
User home directory = C:\Users\Felhasználó
----------------------------------------------------
c:   clear console window
f:   finalize objects on finalization queue
g:   garbage collect
h:   display this help message
l:   dump classloader list
m:   print memory usage
o:   trigger logging
q:   hide console
r:   reload policy configuration
s:   dump system and deployment properties
t:   dump thread list
v:   dump thread stack
x:   clear classloader cache
0-5: set trace level to <n>
----------------------------------------------------
Initializing applet
Version: 1.8.0_144
Vendor: Oracle+Corporation
OS: Windows+10
OS Version: 10.0
Called setUserInfo
Ending init
