### ISSUE TITLE
Follow up: "Can't get it running"

### ISSUE THREAD

**Issue by TimyTom** [Exslims/MercuryTrade#181]
Thank you for answering this quick.

I had Java latest version installed and running before I posted here. So the problem remains: clicking opens a huge sub folder, but unfortunately does nothing else. Game is in window mode.

**Comment by Exslims** [comment]
Its internal problem coz .jar should run as .exe and don't open yourself archive

**Comment by Exslims** [comment]
try to re-install java

**Comment by TimyTom** [comment]
Still didn’t work. Solved it by downloading an app called JAR_Runner, which in some way made it work.


Tom
