### ISSUE TITLE
Popup window not showing for trades.

### ISSUE THREAD

**Issue by Hookups1** [Exslims/MercuryTrade#184]
Not sure if this is the right place to post this.

I'm having trouble getting the popup window to show up when getting trades pms.

I read the trouble shooting guide but nothing there solved my issues.

I have the directory pathed to the right place C:\Program Files (x86)\Grinding Gear Games\Path of Exile

I have the small menu bar showing up but that's it. 

Also it doesnt run when I start POE i have to manually start it.

I think I might be installing it wrong? I was unable to find directions on the process that worked for me. Like where the files should be located etc. Some links to directions would be helpful.

Seems like an awesome program and I would really like to try it.

Any help is greatly appreciated.

**Comment by Hookups1** [comment]
I don't see many responses to peoples issues. Is there no longer support for this app??

**Comment by Exslims** [comment]
look at discord pls

**Comment by Hookups1** [comment]
Thank you for the response. I went to your discord but it's still not working.

I'm pathed to the correct folder in the app. I deleted the folder out of appdata and started over but it still doesn't work.

Not sure what I'm doing wrong.

**Comment by Exslims** [comment]
checkout 1.0.3.0 version where I made a small fix associated with the notification panel
