### ISSUE TITLE
[Feature Request]Kick on panel close

### ISSUE THREAD

**Issue by zocke1r** [Exslims/MercuryTrade#185]
it would be rather useful to have the option to kick a player from the party at the same time you send a message to them. for example after you completed a trade with them you thank them and kick them from your party, issue is in the default config, both thanks and kick both close the panel so you would have to do one or the other manually or change the config and press two buttons.

And in a similar vein the option to leave a party on outgoing messages

**Comment by Exslims** [comment]
tos viloation, sorry
