### ISSUE TITLE
Grid Item cell panel location

### ISSUE THREAD

**Issue by Odin099** [Exslims/MercuryTrade#187]
the location of the Item cell panel hides the top 50% of my stash tabs, so i can only read small letters but only 50% of my big letters. is there any way to move the panel higher?
here a small pic from what i mean:
https://picload.org/thumbnail/dgallwrw/griditemcellpanellocation.jpg
https://picload.org/view/dgallwrw/griditemcellpanellocation.jpg.html

changing resolution for the game or size of the panel dont change anything
my resolution is 3840x2160 (tested 1920x1080 and 1280x1024)

**Comment by Exslims** [comment]
in plans rework grid feature where this problem will disappear
