### ISSUE TITLE
Can't use chat window

### ISSUE THREAD

**Issue by Lyrad8791** [Exslims/MercuryTrade#188]
Whenever I use the app currently, and after a clean install, I am unable to use chat. It constantly spams the chat window with the /hideout command. I have tried changing between the executable and the jar, removed all files and started fresh, and looked through the configs and have yet to find a way of using the program and still having the ability of using chat.

I hope this can be resolved soon. There is no attached log because there is no error. I am not using any other hotkey programs like trade macro or anything.

**Comment by Exslims** [comment]
try to rebind /hideout hotkey (settings -> taskbar -> press on hotkey button -> press esc)

**Comment by Lyrad8791** [comment]
There seems to be no hotkey section in any config area within the taskbar. It also seems to be having issues connecting to the server to check for updates.

**Comment by Exslims** [comment]
download latests version from github please, server are down

**Comment by Lyrad8791** [comment]
I am using the latest version updated 19 days ago according to your latestrelease link. I found a spot in the configuration.json file in the appdata folder. I removed it from being Enter by deleting the word. I hope this will work for the time being.

**Comment by Lyrad8791** [comment]
That resolved my issue.
