### ISSUE TITLE
Still doesn't send notifications

### ISSUE THREAD

**Issue by sherifusa1988** [Exslims/MercuryTrade#189]
I tried the whole troubleshooting solution of the below problem
"Problem: Notifications don't pop-up when receiving a trade messages.

Fix: Please make sure you've selected the correct Path of Exile folder.

if you delete MercuryTrade folder from %userprofile%/appdata/local, run poe client + run mercury, game path will be found automatically"

the path of exile folder is correct, but still, no notifications are received not from trade or even the "chat scanner"

**Comment by Trendkillgaming** [comment]
I don't know if you have done this, but set a shortcut to "run as administrator" For some reason mine wouldn't work either until I did that.

**Comment by sherifusa1988** [comment]
nevermind, it worked after using the .exe file not the .jar one
thx for the reply though
