### ISSUE TITLE
currency trading

### ISSUE THREAD

**Issue by sebyg666** [Exslims/MercuryTrade#193]
ok so when trading large amounts of currency the notification pannel replaces extra characters with ... on the section of what "I" have to give, for example 300 jewellers would show as 3... and i have to look back through chat. doesnt matter how i change the notification pannel zoom, it doesnt change it. 
Can you make it so numbers ALWAYS show in full no matter the length please?

![image](https://user-images.githubusercontent.com/4015191/31011461-3ed25032-a506-11e7-9b36-c7111778ffa7.png)

**Comment by Exslims** [comment]
fixed in 1.0.3.0
