### ISSUE TITLE
Overlay Invisible/Offscreen

### ISSUE THREAD

**Issue by FirePenguinMaster** [Exslims/MercuryTrade#196]
I recently bought a new monitor which changed my resolution. I wanted to reset Mercury Trade so I could make sure all the elements were where I wanted them, but "Restore default location" completely lost all overlay elements. Any way to fix this?

**Comment by Exslims** [comment]
the easiest way is return configuration to default settings by deleting %userprofile%/appdata/mercurytrade folder

**Comment by FirePenguinMaster** [comment]
Just wanted to pop back in to let you know that this worked perfectly. I'm back up and running — thanks much!
