### ISSUE TITLE
Mouse doesn"t work in vmware

### ISSUE THREAD

**Issue by DarkSquad** [Exslims/MercuryTrade#197]
Hello my problem is that when i run poe on vmware and i run mercury i can move mosue but right and left mosue buttons stop working only  clsoe program helps any ideas? It works well before on windows 7 but atm i use win 10 and i got this problem

**Comment by Exslims** [comment]
i have no idea, very weird problem and I can't help you(

**Comment by DarkSquad** [comment]
no problem i already solved that. Problem was with lastest version of your
software i just installed few version behind and its works fine now

2017-10-25 20:30 GMT+02:00 Konstantin <notifications@github.com>:
