### ISSUE TITLE
Weird behaviour when inventory and or stash is open

### ISSUE THREAD

**Issue by leet0rz** [Exslims/MercuryTrade#208]
Sometimes when I click the buttons on the interface while being in stash or having inventory open it will switch weapon/do nothing or not sending the command correctly. Maybe u guys already know about it, thanks :)

**Comment by Exslims** [comment]
issue still exist?

**Comment by leet0rz** [comment]
Yeah, it happens when chat is open as well. Maybe its impossible to fix if it tries to open the chat when its already open with ctrl+v, which would only make it press v and switch weapons in my case because my wep switch is on V. I donno how it works if i rebind it to another key.
