### ISSUE TITLE
[Request] Connection to pushbullet

### ISSUE THREAD

**Issue by gdneye** [Exslims/MercuryTrade#215]
Recently discovered Mercury Trade and its an amazing program, thank you for building it.  One feature it is missing (I think, haven't explored it 100%) and that I would like to request is the ability to send messages to my phone (allows me to pay attention to trades when I'm e.g. doing housework) via pushbullet.

Poe Whisper Notifier [https://github.com/Kapps/PoEWhisperNotifier] has a lot of crossover with your "Chat Scanner" and "Notification History" features but includes the pushbullet feature (currently the pushbullet feature is the only reason I'm holding on to Whisper Notifier).  Whisper Notifier also includes a filter so you can choose which messages will be send to pushbullet.

**Comment by Exslims** [comment]
I don't think MT need it right now but in the future maybe
