### ISSUE TITLE
mercury trade ON but no responses or notification 

### ISSUE THREAD

**Issue by Fayyya** [Exslims/MercuryTrade#223]
Hi , 

downloaded mercury trade , work fine with poe starting( i have the "overlay" , i can change settings  , notifications placement .

my issues are : 

-buttons ( visit hidehout etc ) don't work when notification want to appear 
-0 notifications for trade ( buy and sell )

i'm playing in windowed fullscreen... tested windowed => same issues  

do i have to put the executable somewhere in poe files ? ( playing poe on steam ) 

is there a way to fix these issues ? 

thanks

**Comment by Exslims** [comment]
1. use alternative launcher (run .exe as admin)
2. check game path in settings (i think you have wrong path to game)
