### ISSUE TITLE
UI works but buttons doesn't seem to

### ISSUE THREAD

**Issue by joelm3103** [Exslims/MercuryTrade#236]
Since yesterday (I'm not aware of any updates) anytime I get a trade, the UI pops up as usual but if I hit a button, nothing happens. Click invite, nothing, trade, nothing, etc etc.

**Comment by Sklifan** [comment]
Please check if your chat is active while you are using the buttons (shouldn't be the case), this sounds like a local problem.
Please check the solutions in https://github.com/Exslims/MercuryTrade/wiki/Troubleshooting as well.

**Comment by joelm3103** [comment]
Normally no. If I'm playing and someone whispers I see the UI pops up and see their message but the chat isn't selected.

Also tested another other trade tool I used before to see if it was the tool itself or my game...seems to be my game. Not sure why it doesn't auto enter the invites or messages and sends them...it looks like it opens the chat in a flash but nothing afterwards.

Edit: Now tried it both highlighting chat and without and neither works. Prompt comes up but button refuses to do anything. Also this is after I reinstalled it (deleting the files from appdata/local)
  
Edit2: Tried running the exe file included in the rar archive as admin but it doesn't help either.

Edit3: https://github.com/Exslims/MercuryTrade/issues/69

This seems to be the same issue I'm having.

Edit4: Just used Mercury for an outgoing trade, UI worked, first button to go to their hideout worked but nothing else after that, couldn't trade or leave party etc.
  
  Edit5: Joined Mercury Discord and saw a fix/workaround posted where you disable "put tooltip results on clipboard" from PoE Trade Macro. Shall try and update when I get time.

**Comment by joelm3103** [comment]
https://github.com/Exslims/MercuryTrade/issues/69

This seems to be the same issue I'm having.

**Comment by joelm3103** [comment]
It works after disabling the tooltip copy, sweet :).

**Comment by Sklifan** [comment]
As I said -> "Please check the solutions in https://github.com/Exslims/MercuryTrade/wiki/Troubleshooting as well."

>> (the first step on this :D)
"Problem: Buttons don't work (if you use poe trade macro)
Fix: Uncheck "Put tooltip results on clipboard" in the iteminfo tab in poe trade macro."

Happy trading ;)
