### ISSUE TITLE
Leaving from party when buying items

### ISSUE THREAD

**Issue by Dasky14** [Exslims/MercuryTrade#239]
When you whisper someone to buy something, then try to leave the party by clicking the icon in buy window, it only gives the message "The target of this operation was not a party member". I have to manually leave parties instead.

When someone joins my party and then I kick them, that works fine. Leaving someone else's party doesn't work.

**Comment by Sklifan** [comment]
Check the char/nick-name in Mercury Trade (Settings > Notification panel > "Your nickname [for leave option)], you can only kick "yourself" when the name/nick is correct (for the nickname that is currently logged in, that's not the same as account-name).
