### ISSUE TITLE
jnidispatch.dll Error

### ISSUE THREAD

**Issue by ADRDev** [Exslims/MercuryTrade#24]
This is more of an informative post than an issue. But, I thought it might be helpful.

I'm on Windows 10 and I couldn't get MercuryTrade to launch either from exe or jar. I tried running jar from commandline to see the error

`Exception in thread "main" java.lang.UnsatisfiedLinkError: com.sun.jna.Native.pointerSize()I
        at com.sun.jna.Native.pointerSize(Native Method)
        at com.sun.jna.Native.<clinit>(Native.java:88)
        at com.mercury.platform.core.User32.<clinit>(User32.java:15)
        at com.mercury.platform.core.AppStarter.<init>(AppStarter.java:30)
        at com.mercury.platform.AppMain.main(AppMain.java:17)`

Turns out, the issue was another application I have installed (namely FileBot) had a copy of `jnidispatch.dll` in it's program directory. Once I got rid of that file MercuryTrade launched fine.

So, I think it only happens if you have an incompatible version of `jnidispatch.dll` being loaded from your PATH.

**Comment by Exslims** [comment]
Hmm, thanks for the report, I'll see how to fix it.

**Comment by Exslims** [comment]
extreamly rare problem, in the future i plan to rewrite the native code associated with this problem and maybe this problem will disappear.
