### ISSUE TITLE
Constant loading/not opening program

### ISSUE THREAD

**Issue by ghost** [Exslims/MercuryTrade#242]
Since a few days ago my MercuryTrade stopped working. No changes has been made to computer, windows, etc. MercuryTrade constantly loads, the blue/green'ish circle, just constantly loops and the program never boots up.

I run the .exe version, never ran it as admin previously.

I have tried to delete the program itself, deleted the registry paths relating to mercurytrade, ran as both admin and non-admin. No results.. any suggestions?

**Comment by Sklifan** [comment]
Hey,
I had the same behavior after changing the monitor/resolution.
Try the steps from the trouble-shooting:
"Problem: I need to hard reset the application.
Fix: Go to %userprofile%/appdata/local and delete MercuryTrade folder."
as well check the other steps->
https://github.com/Exslims/MercuryTrade/wiki/Troubleshooting

**Comment by ghost** [comment]
Thanks dude, it helped!
