### ISSUE TITLE
make  buttons in notifications window work with steam version

### ISSUE THREAD

**Issue by Smeagol001** [Exslims/MercuryTrade#246]
i cant use any of the buttons to wisper joinleafe etc in the notification window when i click on them nothing happens

**Comment by Exslims** [comment]
use alternative launcher (run .exe as admin)

**Comment by Smeagol001** [comment]
soo there is no way around than using hte standalone client than it wont recognizr steam achiefments etc-.-

**Comment by Exslims** [comment]
alternative launcher of **MercuryTrade**

**Comment by Smeagol001** [comment]
were do i find this alternate launcher or are you talking abaut the .exe


2018-01-23 17:27 GMT+01:00 Konstantin <notifications@github.com>:

**Comment by Exslims** [comment]
https://github.com/Exslims/MercuryTrade/blob/master/README.md
