### ISSUE TITLE
Wrong User posting?

### ISSUE THREAD

**Issue by KCIV** [Exslims/MercuryTrade#25]
Sometimes when trade traffic is heavy (or even not) it will double post to 2 users in the same line 

Example @user/kickUser instead of /kick user

here is an example where it was stacking string.

https://puu.sh/uHFbE/339e2ba13f.png

I have noticed that often after using the app I will press enter, and a @user will be sitting there.

**Comment by KCIV** [comment]
I tested allowing between 2-5 hard counted seconds and the issue still presented itself.

It could be the heavy traffic, I average 2-3 message in a raw second.

**Comment by KCIV** [comment]
Its important to note, it only happens on kicking/inviting/whispering in any order and solo operations.

has never happened on a trade invite.

I have ONLY tried to kick someone (after clearing chat) and it did this, I have tried whisper then kick or kick then whisper few other things. 

I also tried it with kick NOT closing same issue.


Actually just tested this by clearing chat after every command, and occasionally without prompt, the program will start to type out (a second time) the last operation made.

I would whisper, clear chat, chat would start to type out @ command again, clear it, kick, the program would start to type out a kick command.

**Comment by Exslims** [comment]
Thanks for reply, I'll try to fix it and add some more tools in the next update to make it easier to see what is the error.

**Comment by Exslims** [comment]
will fixed in 1.0.0.7 i hope

**Comment by KCIV** [comment]
Yay awesome work sir!
