### ISSUE TITLE
How to build the project

### ISSUE THREAD

**Issue by benjy3gg** [Exslims/MercuryTrade#26]
Can you write a quick how-to on building the project?

**Comment by Exslims** [comment]
just for installing and download all dependencies: cd MercuryTrader; mvn clean install in terminal

**Comment by Exslims** [comment]
ofc you need Maven v3+

**Comment by benjy3gg** [comment]
`Failed to execute goal on project app-core: Could not resolve dependencies for project com.home.mercury:app-core:jar:1.0.0.5: Could not find artifact com.home.mercury:app-shared:jar:1.0.0.5 in central (https://repo.maven.apache.org/maven2) -> [Help 1]`

**Comment by Exslims** [comment]
Go to app-shared pom and add `<parent>` section like in other modules.
Go to root pom and uncomment   ` <!--<module>app-shared</module>-->`

**Comment by benjy3gg** [comment]
Is this commented intentionally?

**Comment by Exslims** [comment]
yes, because i need installed app-shared.jar to other application.

**Comment by Exslims** [comment]
u can try other solution, just cd app-shared; mvn clean install

**Comment by RUSshy** [comment]
> yes, because i need installed app-shared.jar to other application.

why do that in master and not in your local repo

it makes user experience for people to contribute so bad

i followed what is written here and i still can't compile or use or contribute this project

so far experience is really bad

**Comment by Exslims** [comment]
@RUSshy I may be wrong after all this time but you just need to install app-shared separately (cd app-shared, mvn clean install) and then build the main project..
