### ISSUE TITLE
Buttons don't type text 

### ISSUE THREAD

**Issue by pringprang** [Exslims/MercuryTrade#27]
While using the steam version, text box opens up without inputting any text at all and closes itself instantly. Applies to all buttons that send text.

**Comment by etofok** [comment]
have you tried the other launcher we made? please run it as admin and report back

**Comment by pringprang** [comment]
I have, it does the same thing as the jar file. There was 1 time where I was spamming the hideout button and I got the error of not being able to teleport to hideout, but other than that, everything else tries to input it into chat but nothing goes through.

**Comment by Exslims** [comment]
@pringprang provide pls app.log file from the %userprofile%/appdata/local/MercuryTrade folder

**Comment by pringprang** [comment]
Sorry for the wait, I believe this is the right file. Thanks for your time.
[applog.zip](https://github.com/Exslims/MercuryTrade/files/844762/applog.zip)

**Comment by pringprang** [comment]
More info, I tried it again today. When I press the whisper button, it opens up chat but it uses my abilities' hotkeys instead and leaves the chat box open. Example being is that I have my aura on space bar and the whisper button toggles it. Happens for all active skills like shield charge and flame dash.

**Comment by Exslims** [comment]
we can't know opened chat or not,  code pushes enter-> ctrl+v -> enter, if your chat has already openned it's just close chat after first enter

**Comment by pringprang** [comment]
I leave the chat closed at all times, I noticed the buttons don't work when I leave it open.
