### ISSUE TITLE
UI offscreen

### ISSUE THREAD

**Issue by HennerOr** [Exslims/MercuryTrade#28]
Everything works fine but the Overlay UI is offscreen for some reason

**Comment by Exslims** [comment]
Notification panel and Task panel? have you tried to press the "Restore default" button in pin mode?(1st button on task panel)

**Comment by HennerOr** [comment]
Cant see either of the panels, so i cant reset it to default.

**Comment by Exslims** [comment]
Hmm, I'll try to fix it but now u can only remove MercuryTrade folder from %userprofile%/appdata/local for hard reset. Thanks.

**Comment by HennerOr** [comment]
This might seem wierd, but i dont have any appdata for MercuryTrade. Unless im looking in the wrong place.

**Comment by Exslims** [comment]
AppData/Local/MercuryTrade

**Comment by HennerOr** [comment]
http://pokit.org/get/?0baee71629eaee32dae3c0a0562aa06c.jpg

Its Cleared Unless the pathing is wrong.

**Comment by Exslims** [comment]
I think you're looking at the wrong user

**Comment by HennerOr** [comment]
Interesting it was under another user but i couldn't see it without typing "\AppData" manually, deleted the MercuryTrade folder so it should be fixed now. Thanks!
