### ISSUE TITLE
MercuryTrade does not load

### ISSUE THREAD

**Issue by TJEmvp** [Exslims/MercuryTrade#284]
Hi,

I have used MercuryTrade many times in the past and never had any issues.
Right now MercuryTrade does not load, I only see the logo making nice circles 24/7.

I did the following:

- Reinstall POE
- Reinstall MercuryTrade
- Reinstall Java

I have no clue what to do, but I really hope someone here knows a solution?
Why does it not load?

:((

**Comment by Exslims** [comment]
download latest version (1.0.3.3)
