### ISSUE TITLE
Invisible UI

### ISSUE THREAD

**Issue by elvese** [Exslims/MercuryTrade#293]
Recently something happend and i cant see UI menu, any fix ?

**Comment by Exslims** [comment]
close via tray icon and start again

**Comment by elvese** [comment]
i tried many times, also restarting pc doesnt help.
Funny thing is its still working, when i whisper some1 window pops out but menu gone, cant setup my chat filter etc :/

**Comment by Exslims** [comment]
tryt to reset components locations via tray icon

**Comment by elvese** [comment]
im clicking restore redault location and no effects :(

**Comment by elvese** [comment]
Does mercury writes any config file that i can delete ?

**Comment by Exslims** [comment]
%userprofile% appdata local MercturyTrade folder delete pls

**Comment by elvese** [comment]
WORKED !!
