### ISSUE TITLE
MercuryTrade won't pop up or play any sound!

### ISSUE THREAD

**Issue by Dam96** [Exslims/MercuryTrade#294]
Hello! Moved my PoE from HDD to SSD last night and now my Mercury trade wont work! I've tried editing the path, removing old folder from %appdata%, deleted it and resinstalled it. Still dosn't work.
It works when i use the "test incomming message". All hotkeys work.
Any advice or anyone have had the same problem?
Best regards

**Comment by Exslims** [comment]
close MT and POE, remove MercuryTrade folder from %userprofile%/local -> start poe -> start MT

**Comment by Dam96** [comment]
Tried it before, did it again, still dosn't work.
