### ISSUE TITLE
Option to "open" the stack when that user enters your HO.

### ISSUE THREAD

**Issue by olafurw** [Exslims/MercuryTrade#30]
Currently they are all stacked and closed but it would be helpful to have an option to open the stack item when someone enters your HO.

**Comment by etofok** [comment]
this might be troublesome with notifications that are grouped thus requiring a huge rework of the whole system. I'll check anyway

you can set up "Unfold by default" in notification settings (unpin panels)

**Comment by olafurw** [comment]
Ahh I had forgotten about the options in the "lock" setting part of the application. Browsed through normal settings like 100 times.
