### ISSUE TITLE
Option to remove the stack item when a user that was in your HO has now left it.

### ISSUE THREAD

**Issue by olafurw** [Exslims/MercuryTrade#31]
He has entered your HO and now has left it, option to remove the stack item when he leaves your HO. I saw that there is one option to remove on group leave which is good.

**Comment by etofok** [comment]
a) you left your ho first aka went back to mapping asap - still have to manually dismiss
b) the guy decided he really likes your ho to live here from now on - still have to manually dismiss
c) he left before the trade happened (dced or whatever) - have to pull the notification back from history

It's definitely not a difficult thing to implement but its unreliability bothers me.

**Comment by olafurw** [comment]
If some of the edge cases fail you can go back to standard behavior since a lot of cases the normal case is what is going to happen.
