### ISSUE TITLE
Option to pin one message to the closed stack item

### ISSUE THREAD

**Issue by olafurw** [Exslims/MercuryTrade#32]
So when you get a lot of messages for an item that has been sold, it would be handy to pin one of your messages to the closed stack item so you can send "Sold" quickly without having to open the stack item and send the msg and then remove it.

Or even "Send message and remove stack item" as an option for "Sold" and remove it from the stack.

**Comment by etofok** [comment]
you can set up "close on response" in settings already

**Comment by olafurw** [comment]
Ahh wow ok that checkbox with close did not confuse me at all.... :P

**Comment by etofok** [comment]
if you have a better idea how to indicate this functionality please let me know
