### ISSUE TITLE
Whisper pop up window not working

### ISSUE THREAD

**Issue by Jihtsofox** [Exslims/MercuryTrade#320]
I was using mercurytrade on 3.4 installed on alternate hard drive using steam, when 3.5 was about to release I deleted the steam version and re-installed poe on my SSD as the stand alone version. After the 3.5 patch the whisper notification window would not show, but would make a sound (menu bar is fine). 
I've tried deleting the history and folder as suggested, running both the .jar and .exe and still is not working. Any help or suggestions would be appreciated as this is an amazing program. 

Thanks.

**Comment by Jihtsofox** [comment]
Also tried older versions, running as admin etc...nothing brings it back...

**Comment by armando-g** [comment]
Open the panel mover window and move the whisper notification window a little bit, then lock it again. It will come back.

**Comment by Jihtsofox** [comment]
The problem is since the update to 3.5 it doesn't show at all when I get a whisper...but I tried what you said..thanks

**Comment by Jihtsofox** [comment]
Fixed, one of the things I did fixed it and it is now working, thank you.
