### ISSUE TITLE
4k resolution - Some core buttons are cut off

### ISSUE THREAD

**Issue by pdufour16** [Exslims/MercuryTrade#33]
The app is impossible or very difficult to use on 4k screens. most of the buttons are cut off on the bottom right side. Might want to do scalable interfaces?
<img width="140" alt="example" src="https://cloud.githubusercontent.com/assets/24961736/23950107/3fc4e4f6-0960-11e7-8c62-a8f690d1f963.PNG">

**Comment by etofok** [comment]
bigger UI is a common request, we'll do something about that
