### ISSUE TITLE
How to change syndicate rewards matrix overlay image?

### ISSUE THREAD

**Issue by VeinPump** [Exslims/MercuryTrade#336]
Hi,
I appreciate that you added syndicate rewards overlay, but I have my own image I'd better to work with
Is there an opportunity to change this image? All I found in the MercTrade folder from images are only cursors (mb didn't find correct folder?)
Thanks

**Comment by Exslims** [comment]
you can try to open the jar with WinRar and replace helpIGImg.png image in app folder
