### ISSUE TITLE
Suggestion: Option to kick party members on response button

### ISSUE THREAD

**Issue by Ninjaskill** [Exslims/MercuryTrade#34]
Would love if there was a check box to kick party member on response button. Like T4T also kicks the player from group.

**Comment by etofok** [comment]
you can kick first and then say thx. we can't do 2 server actions on one click rn (TOS)

**Comment by Ninjaskill** [comment]
Oh, really? There was an original PoE trade helper that did and it was approved by GGG. The app had an option to link kick from group to response buttons,.Is that not allowed after all?

**Comment by etofok** [comment]
It's not allowed. https://github.com/lemasato/POE-Trades-Helper/wiki/FAQ
