### ISSUE TITLE
Export history of sold items

### ISSUE THREAD

**Issue by vajura** [Exslims/MercuryTrade#35]
Could you implement a way to export the history of all your sold items?

**Comment by etofok** [comment]
Mercury tracks offers, not trades. The app only reads your chat so it doesn't know what kind of a trade you've made. It's possible though to add a button like "Successful Trade" that will push that notification into some list of successful trades and work from there, but right now there are other priorities to be implemented first.

**Comment by vajura** [comment]
The trade history is alredy saved in some file though right? Could you point me to it maybe?

**Comment by Exslims** [comment]
history.json in %userprofile%/AppData/Local/MercuryTrade
