### ISSUE TITLE
Change the Syndicate Picture to another Picture

### ISSUE THREAD

**Issue by d3stroza** [Exslims/MercuryTrade#351]
How do I change the current Syndicate Picture to: 
![2u8dnehxbubp3yq-kwjckrn7a2s5newx5df39ha0nmi](https://user-images.githubusercontent.com/47029029/51743199-3a808900-209c-11e9-8b87-e436086b7fd2.png)

I've looked through pretty much every folder but couldn't find any specific image data. Where is it located?

**Comment by d3stroza** [comment]
Okay so I finally found it:

In Case anyone else wants to change it:

I've opened MercuryTrade.jar with WinRAR, used the Search Engine, found it immidiately, renamed the new data into "helpIGImg" and replaced it with the old one.

**Comment by AnnanFay** [comment]
@d3stroza What's the source of the above image? I'd like to use it but would like to use the most up to date from the author if there's a new version.

**Comment by d3stroza** [comment]
@AnnanFay I've found it here: https://www.reddit.com/r/pathofexile/comments/aczmcb/clean_poe_reference_sheet/

it's a pretty old picture from Syndicate League.

**Comment by AnnanFay** [comment]
Thanks!
