### ISSUE TITLE
Error parsing buy message

### ISSUE THREAD

**Issue by rainbowism** [Exslims/MercuryTrade#37]
Case of an incorrectly parsed name, seemingly caused by an escaped character?

Log line in question:
```2017/03/18 04:25:13 248468954 951 [INFO Client 7312] @From <:\/> No_AoE_Allowed: Hi, I would like to buy your Superior Wharf Map listed for 1 alchemy in Legacy (stash tab "~b/o 1 alch"; position: left 7, top 10)```

![Escaped Character](https://puu.sh/uOgHD/ad9231cf5f.png)

**Comment by Exslims** [comment]
fixed in 1.0.0.7
