### ISSUE TITLE
Path of Exile window goes to background randomly

### ISSUE THREAD

**Issue by ghost** [Exslims/MercuryTrade#39]
Throughout the game, PoE.exe (which is borderless fullscreen) randomly goes to background, losing focus. I can fix everything by selecting another window, like Chrome and then going back to PoE. I'm 100% sure it happens only when MercuryTrade is running. The bug is quite frequent as well.

P.S. Version 1.0.0.6

**Comment by Exslims** [comment]
how often does this happen

**Comment by ghost** [comment]
I would say every 10-15 minutes

**Comment by Exslims** [comment]
it's very strange, we will investigate, but unlikely to be fixed in 1.0.0.7, no one said anything about bugs like this, maybe some other scripts do it?

**Comment by ghost** [comment]
Nope, I tested multiple scenarios, thinking it was Windows 10, but pretty sure it's MercuryTrade. One thing I should mention is that the bug didn't exist before 1.0.0.6

**Comment by Exslims** [comment]
hm, we pushing 1.0.0.7 today, mb can be fix, let me know

**Comment by ghost** [comment]
Hasn't changed as of 1.0.0.7, I'm afraid.

**Comment by etofok** [comment]
looks like you have a local conflict of some sort, can you try to shut down everything non-essential but poe + mercury and check? shift+alt+esc 

keep us updated as this issue is extremely rare.

**Comment by ghost** [comment]
I've been trying out different things. It seems that Skype Preview was an issue. I haven't noticed it before because it was pretty much at the bottom of the Task Manager. It's been an hour since I killed the process and MercuryTrade hasn't bugged out yet. I'm not sure whether Microsoft has updated the app, but if so, they could've broken something. I'll let you know if anything changes.
