### ISSUE TITLE
[feature request] Allow customization of the syndicate sheet

### ISSUE THREAD

**Issue by tbarusseau** [Exslims/MercuryTrade#390]
It's currently possible to customize the syndicate sheet by unpacking the JAR, changing the `<JAR>/app/helpIGImg.png` file, but being able to change it through the GUI would be better in my opinion.

**Comment by ngbtri** [comment]
> It's currently possible to customize the syndicate sheet by unpacking the JAR, changing the `<JAR>/app/helpIGImg.png` file, but being able to change it through the GUI would be better in my opinion.

Thank you for sharing this method. I did this just fine 💃 
How would you go about doing that in rar version?

**Comment by Exslims** [comment]
Hi, can you share updated cheatsheet?

**Comment by ngbtri** [comment]
> Hi, can you share updated cheatsheet?

https://www.reddit.com/r/pathofexile/comments/ekjv21/syndicate_cheat_sheet_39_prices/?utm_medium=android_app&utm_source=share

I found it here on reddit. 

I used the color version, direct link: http://imgur.com/KpSJB1j

**Comment by Exslims** [comment]
Thanks! I'll publish versions with an updated sheet...

**Comment by ngbtri** [comment]
Thank you! Would be great if you could de-couple the image from the distribution and allow us to specify a custom image (say in the same folder as the jar and the rar) - what op said :D

**Comment by Exslims** [comment]
This takes more time to do than replacing img file :) but you still can to do it by yourself

**Comment by Exslims** [comment]
https://github.com/Exslims/MercuryTrade/releases/tag/1.0.3.6
