### ISSUE TITLE
[Request]Suported wildcard in chat messages.

### ISSUE THREAD

**Issue by Nipper4369** [Exslims/MercuryTrade#44]
What I mean by this is like 
%Item% = Item there looking for 
%Cost% = Being what it was going to be sold for 
%User% = Being the person looking for the item.

Reason being so it can feel more friendly and personalized messages.
 
Example: 
They message you
@JoeBlow Hi, I would like to buy your Reach of the Council Spine Bow listed for 25 exalted in Legacy (stash tab "$$$"; position: left 11, top 11)

You reply with 1button reply
@JoeBlow Sorry, JoeBlow the item "Reach of the Council Spine Bow" was already sold for 25 exalted.

Or just

@JoeBlow Sorry, JoeBlow the item "Reach of the Council Spine Bow" was already sold.

Or 

@JoeBlow Let me check to see if I still have the Reach of the Council Spine Bow give me a second to finish up here.

**Comment by etofok** [comment]
We wanted to simplify HUMAN interactions. These messages sound ridiculously bot-like and none of the players I know enjoy receiving these kinds of responses. A simple "ty" is waaay better than "Thanks for the Reach of the Council Spine Bow, NotAnotherMorsuBuild! These 25 Chaos Orb of yours will be used wisely, exile!".

Basically it's a design choice we want to stick with

**Comment by Nipper4369** [comment]
One would assume. But check this out https://www.pathofexile.com/forum/view-thread/1755148
