### ISSUE TITLE
[Suggestion] Exchange rate on currency trades

### ISSUE THREAD

**Issue by RyanHx** [Exslims/MercuryTrade#47]
When trading currency perhaps between the two currency labels have the exchange rate of the request. Helpful for some janky uneven trades.

Otherwise much appreciate all the work you're putting in!

(attached image example of the area I mean)

![example](https://cloud.githubusercontent.com/assets/19942516/24264961/e383c46e-0ff9-11e7-9798-09996e7bab0f.png)

**Comment by etofok** [comment]
shouldn't you check the exchange rates beforehand anyway? otherwise you'll get spammed to death with offers. Mercury only interacts with the chatlog file - it doesn't check poe.trade / API / anything else. It can be done, but I don't see the point.

**Comment by RyanHx** [comment]
I don't mean the market's current exchange rates, sorry if it was worded poorly. I mean of the specific trade in question, so if someone was making an offer with a different ratio to the one you listed you could immediately tell - say they offered 75 chisel for 25 chaos, instead it would display "3 chisel". It was just a QOL suggestion over having to calculate an offer yourself since it was automating so much of the process already. No worries if not though - was just an idea :)

**Comment by Exslims** [comment]
I will probably add it in 1.0.1.0

**Comment by RyanHx** [comment]
That's great, much appreciated!
