### ISSUE TITLE
bug: after u @someone, the button work failed

### ISSUE THREAD

**Issue by nopcall** [Exslims/MercuryTrade#48]
![w](https://cloud.githubusercontent.com/assets/1996547/24356863/2e912c08-132e-11e7-97cd-a010e96924a9.png)
like that

**Comment by Exslims** [comment]
could you suggest how it can be reproduced

**Comment by etofok** [comment]
Are you sure you close the chat window before pressing buttons? Mercury sends enter-/command-enter, obviously if your chat is already open it won't work properly.

**Comment by nopcall** [comment]
@Exslims 
```
enter
"@someone any message"
enter
```
then click button like kick or sold

**Comment by nopcall** [comment]
@etofok 
after you "@someone some message"
you will get "@someone" as prefix when u press enter
i thinksend enter/ctrl-a/command/enter should fix that

**Comment by Exslims** [comment]
this has been done, it is strange that sometimes fails, 1.0.1.1 will include the "chat commands" fixes.
