### ISSUE TITLE
AutoUpdate Does not work.

### ISSUE THREAD

**Issue by Nipper4369** [Exslims/MercuryTrade#51]
I noticed this before and pass it off as just a minor thing. But with the latest update you hit download it downloads then you hit restart it does not restart and then when you run it again it just popups again with out the update.

**Comment by n4id** [comment]
i have the exact same issue

**Comment by etofok** [comment]
The crux of your problem is the new thing you downloaded haven't replaced the old one. Maybe you guys forgot to unpack the .rar? Or some other weird access related issue. The 99.9999% of the userbase updated just fine which indicates the local nature of your problem. Please describe how you run/launch the application.

**Comment by n4id** [comment]
first i tried just downloading and running the .jar which had the described problem with updating.
now i downloaded the .rar unpacked everything and ran the .exe but the update issue persists.

**Comment by etofok** [comment]
do you run the .exe as admin? Windows? Steam?

Go to %userprofile%/AppData/Local/MercuryTrade
and copypaste everything from these files "_update.log_" AND "_app.log_"

don't copypaste it here, use this instead
https://hastebin.com/

**Comment by n4id** [comment]
there is no update.log 
app.log: https://hastebin.com/metudajeqa.sql
i will try to run it as admin
edit: running it as admin didn't change anything

**Comment by etofok** [comment]
The fact you don't have the "_update.log_" is weird.

Do you have the "_local-updater.jar_"?
Do you have something in the "_temp_" folder?

**Comment by etofok** [comment]
> now i downloaded the .rar unpacked everything and ran the .exe but the update issue persists.

Do you realize this is most likely the last version? Please check your version and report back. Should be 1.0.1.0 / "you have the latest version"

**Comment by n4id** [comment]
> Do you realize this is the last version? Please check your version and report back. Should be 1.0.1.0 / "you have the latest version"

sry i was unclear: when i first downloaded the tool about a week ago i used the .jar. after the update failed i manually downloaded the .rar (the version before the current version)

**
![image](https://cloud.githubusercontent.com/assets/26749904/24427907/e840033e-140c-11e7-852a-a203771bc489.png)
**
![image](https://cloud.githubusercontent.com/assets/26749904/24427979/34023102-140d-11e7-94b5-028a6b826b4b.png)

it seems like the newest version got downloaded to the tempory folder but didn't replace the version in use?

**Comment by etofok** [comment]
For some reason your download haven't been put into main folder.
Just copy that .jar from "temp" to main folder and it should work fine.

Also, if you want to help us a bit do the following:

please in the Window's Path Field (%userprofile%/AppData/Local/MercuryTrade) type in "cmd". This will open cmd with that path as default. Then copy this:
java -jar local-updater.jar C:/Games/MercuryTrade/MercuryTrade.jar

and screenshot that

**Comment by Nipper4369** [comment]
Your right it did download to that temp folder. It just does not copy and replace the jar file. I would hate to have to just do this every time but copying it over did have the newest version.

**Comment by etofok** [comment]
well you can participate in resolving this issue if you go through the aforementioned steps in the post above

**Comment by n4id** [comment]
![image](https://cloud.githubusercontent.com/assets/26749904/24430611/b3a0df80-1417-11e7-8a84-ef11a1731219.png)

i'm afraid thats not what you hoped for

**Comment by Exslims** [comment]
please in the Window's Path Field (%userprofile%/AppData/Local/MercuryTrade) type in "cmd". This will open cmd with that path as default. Then copy this:
java -jar local-updater.jar C:/Games/MercuryTrade/MercuryTrade.jar

not win + r

**Comment by n4id** [comment]
![image](https://cloud.githubusercontent.com/assets/26749904/24430737/75ec2522-1418-11e7-90b0-eee1841976ec.png)

**Comment by Exslims** [comment]
now it updated? thanks a lot for help. i will see

**Comment by n4id** [comment]
![image](https://cloud.githubusercontent.com/assets/26749904/24430831/e595115e-1418-11e7-8966-f053c1a141d5.png)

yep it copied the jar from the temp to the folder

**Comment by etofok** [comment]
thanks for the info

**Comment by n4id** [comment]
glad i could help! really enjoy the tool! ty!
