### ISSUE TITLE
Scaling = two frame instances

### ISSUE THREAD

**Issue by sicu** [Exslims/MercuryTrade#52]
![merc-double](https://cloud.githubusercontent.com/assets/26230029/24439139/a62a6896-144c-11e7-9346-e876d21bb171.jpg)
Scaled the main bar down to 90% and then went to move it a little and behind it was a second frame. I see two instances of Merc running. Will try to duplicate the issue and get back to you

**Comment by Exslims** [comment]
i think u just open 2 MercuryTrade)

**Comment by sicu** [comment]
yeh, has not happened again, so must likely one was already in the 'hidden icons' taskbar and I didn't notice. So closing this 👍
