### ISSUE TITLE
Support message format for poeapp.com

### ISSUE THREAD

**Issue by poeapp** [Exslims/MercuryTrade#54]
Message format:
`wtb {{item}} in {{league}} (stash "{{stash}}"; left {{x}}, top {{y}})`

If the item has a price then `{{item}}` is appended with: ` listed for {{amount}} {{currency}}`

#### Currency Names (these currency names are also used in my poe trade equivalent message)
```
Blessed Orb
Cartographers Chisel
Chaos Orb
Chromatic Orb
Divine Orb
Eternal Orb
Exalted Orb
Gemcutters Prism
Jewellers Orb
Mirror of Kalandra
Orb of Alchemy
Orb of Alteration
Orb of Augmentation
Orb of Chance
Orb of Fusing
Orb of Regret
Orb of Scouring
Orb of Transmutation
Portal Scroll
Regal Orb
Scroll of Wisdom
Vaal Orb
Perandus Coins
```

Examples:  
`@WielkiCymbaw wtb Shavronne's Wrappings Occultist's Vestment listed for 7.5 Exalted Orbs in legacy (stash ">=10c"; left 11, top 5)`  
`@FireBallszzzz wtb Shavronne's Wrappings Occultist's Vestment in legacy (stash "crafting"; left 11, top 10)`  

Gems have a ` ({{level}}/{{quality}}%)` following the name:  
`@BoomBoomiee wtb Molten Strike (1/0%) listed for 1 Orb of Alteration in legacy (stash "Gems"; left 2, top 5)`

**Comment by Exslims** [comment]
@poeapp sorry for the long absence, in the templates nothing has changed?

**Comment by poeapp** [comment]
No worries and yes, the templates are still the same.

**Comment by Exslims** [comment]
@poeapp maybe you have regexp patterns? to me not to waste time)

**Comment by poeapp** [comment]
Maybe something like this will get you most of the way there:

```
/wtb\s+?(.+?)\s+?in\s+?(.+?)\s+?\(stash\s+?"(.*?)";\s+?left\s+?(\d+?),\s+?top\s+(\d+?)\)(?:\s+?listed for\s+?([\d\.]+?)\s+?(.+))?/
```

**Comment by Exslims** [comment]
@poeapp thx

**Comment by Exslims** [comment]
@poeapp added in 1.0.1.6
