### ISSUE TITLE
Support for Russian and other languages

### ISSUE THREAD

**Issue by Archet1337** [Exslims/MercuryTrade#58]
I have noticed that whenever I get a message from someone with a russian/arabic/thai name, Mercury Trade will not trigger and I have to do the trade manually. Will you be adding support for these languages as well?

**Comment by Exslims** [comment]
hello, what is your version? its already done after 1.0.0.8 version.(now 1.0.1.0)

**Comment by Archet1337** [comment]
I must have had an older version. Updated to 1.0.1.0 now. Thanks.
