### ISSUE TITLE
1.0.1.1 Close trade notification with x not working.

### ISSUE THREAD

**Issue by sclient** [Exslims/MercuryTrade#59]
^Pretty much says it, I usually x out of trades since I mostly just use MT for the logging, and just updated to the new version.

**Comment by Exslims** [comment]
hi, can u provide app.log from %userprofile%/appdata/local/MercuryTrade, copy&paste content to hastebin.com.

**Comment by etofok** [comment]
@sclient you can restart the app as a temp solution

**Comment by Turambar87** [comment]
Hello, i've had the same problem yesterday, while flipping currency, it would happen randomly and when someone spammed the same message twice (idiots =D).
Also, i had problem with the auto update, it did download the new version, but after reaching 100% and clicking on restart, it would just simply crash and when restarting, it would still be the unupdated version.
Thanks for the awsome app btw, little bugs but works like a charm!!!

**Comment by Exslims** [comment]
First problem was fixed in 1.0.1.2, update issue will be fixed in next version. Thanks.
