### ISSUE TITLE
Stops working properly after alt tabbing a few times

### ISSUE THREAD

**Issue by kannibleklown** [Exslims/MercuryTrade#60]
Every so often it stops notifying me when someone messages for an item (even tho it's still up and the tool bar is still there) normally after alt tabbing several times.

**Comment by etofok** [comment]
As soon as this happens again please copy-paste everything %userprofile%/appdata/local/MercuryTrade/app.log contains. use hastebin.com

**Comment by kannibleklown** [comment]
Just happened again, got messaged, it's still turned on any doesn't pop up with the box. https://hastebin.com/ozatevogik.sql

**Comment by sclient** [comment]
This bug is affecting me as well.. I just restarted the program, that always fixes it, but here is my info:
https://hastebin.com/atifehebap.hs

**Comment by Exslims** [comment]
what is your mercury version? 1.0.1.1 or 1.0.1.2

**Comment by kannibleklown** [comment]
1.0.1.2, it wasn't happening with the last version, just this new version.

**Comment by Exslims** [comment]
khm, i will try to find what the problem is.

**Comment by kannibleklown** [comment]
I appreciate it. It's not the biggest issue, just a slight annoyance when it happens =p

**Comment by KObeNN** [comment]
Same problem here. My problem is when I use directX 9 and directX 9ex, if I use directX 11, it works perfect

**Comment by kannibleklown** [comment]
hasn't happened to me in a few days, but I was in dx11 when it did happen.

**Comment by Exslims** [comment]
it a permission problem, use an alternative launcher(run .exe as admin).
