### ISSUE TITLE
10.0.1.2 Item grid issues

### ISSUE THREAD

**Issue by sclient** [Exslims/MercuryTrade#62]
I am having some issue getting this feature to work correctly. In a previous patch, when I would save the position, it would have a little box that popped up to dismiss for the tabs Id set positions on, doesn't seem to add them for this patch or the previous one (although the actual position does get remembered), but the bigger issue is that as far as I can see the highlighting doesn't seem to work on either patch for me..

Here is a hastebin of my current log:
https://hastebin.com/tupebapiya.hs

**Comment by Exslims** [comment]
I found a bug when stash tabs are not saved, but why are not there I can't tell yet, thanks for the report.

**Comment by sclient** [comment]
Oh I found out part of my problem.. I wasnt inviting with MT, using another tool, so highlighting doesnt work that way I guess..

**Comment by Exslims** [comment]
you can click on ItemName and highlighting should work.
