### ISSUE TITLE
Mercury takes long time to start then closes immediately

### ISSUE THREAD

**Issue by Kutulue** [Exslims/MercuryTrade#64]
The blue green circle shows for 30 secs.   Then it closes and no Mercury trade windows show up.
I can close it from the taskbar.  Win 7.  Steam Poe

app.log
2017-04-03 23:40:55.492 [nioEventLoopGroup-2-3] ERROR ClientHandler - java.io.IOException: An existing connection was forcibly closed by the remote host

**Comment by Exslims** [comment]
Hi, this error shouldn't affect mercury, if manifests itself once again please provide more information.

**Comment by Kutulue** [comment]
Hmm ok. unfortunately this problem means I cannot use Mercury Trade.  As I
mentioned the mercury taskbar does not open at all.  When whispers occur
Mercury does nothing.
I have tried shutting it down via the windows taskbar and restarting it.  I
tried stopping POE then starting Mercury then starting POE.  Nothing seems
to help.
It was working fine until the most recent update.  Once I rebooted after it
the problems started.

Please let me know if there is more info that might help?

Ian Duncan

**Comment by Exslims** [comment]
hmm, please copy-paste everything %userprofile%/appdata/local/MercuryTrade/app.log contains. use hastebin.com
have you tried previous version of Mercury? 1.0.1.1 or 1.0.1.0

**Comment by Kutulue** [comment]
Hmm I have some more information.  I sometimes run dual clients for more
storage.  My main account is the steam client.
When I run the steam client only Mercury trade fails.  If I start up the
non steam client Mercury trade suddenly starts working.
Once the non steam client is closed down Mercury Trade windows disappear.

Not sure if this helps.

Ian Duncan

**Comment by Kutulue** [comment]
Hi Exslims.  I think I worked out what was causing my issues.  
I had moved the jar file to D:\program files\Mercury trade folder.  I think this stopped it working correctly.  Maybe a permissions issue.  I deleted the appdata merury trade folder and downloaded jar again and it seems to now be working.  Currently running it from my Downloads folder.

**Comment by Exslims** [comment]
Hi, thanks for the reply

**Comment by Exslims** [comment]
the problem with rights is solved by an alternative launcher if you have still problems let me know.
