### ISSUE TITLE
Weird invite button problem

### ISSUE THREAD

**Issue by pjootr93** [Exslims/MercuryTrade#65]
Sometimes when i click on invite button app sends name of item to buyer instead off inviting him to party.

**Comment by Exslims** [comment]
really weird, i will try to find the cause.

**Comment by zbytt** [comment]
Additionaly, when you have opened chat, insted of inviting someone to party,  just writes the name of buyer in local chat

**Comment by etofok** [comment]
When you press a button, Mercury sends "enter - /command / enter" sequence. If you open chat or put something in-focus where you can type - IT WILL NOT WORK.

**Comment by zbytt** [comment]
It's pretty clear for me, but can be confusing for new users

**Comment by zbytt** [comment]
Maybe the solution for this is to display a warning when clicking "enter" when the popup with new trade is displayed ( and disable the invite btn for example ?)

**Comment by etofok** [comment]
Mercury doesn't know about your chat focus state. You can press "enter" during a loading screen or when pricing items or whatever in other words it's not possible for us to track it in a legit way.

**Comment by zbytt** [comment]
Maybe it should be documented somewhere (ofc the truth is that users won't read that anywhay)

**Comment by Exslims** [comment]
in next version will be fixed.
