### ISSUE TITLE
FPS drop when running MercuryTrade

### ISSUE THREAD

**Issue by Play4Fun1** [Exslims/MercuryTrade#67]
I experience fps drop when run MercuryTrade, poe in background fps are good (constants 144 in town), but when foreground fps drops to 65 (in town), i think its for the toolbar overlaying the poe making some issues, idk what to do. (Win 7, recently switch to gtx1070)
Thanks in advance and for the effort doingthat useful tool. :)

**Comment by Play4Fun1** [comment]
Just checked windows aero is off, turn in up and the issue dissapear

**Comment by Exslims** [comment]
thanks, u have 144hz monitor?

**Comment by Play4Fun1** [comment]
yeah have 144 hz monitor, desktop fps is at 144 aswell. Thanks for the reply
