### ISSUE TITLE
Mercury Trade not fully functioning all of a sudden

### ISSUE THREAD

**Issue by Netey88** [Exslims/MercuryTrade#69]
First of all did some research here and didn't find anything similar but saw that u requested this;
https://hastebin.com/anejiboxof.sql

*Mercury Trade worked earlier this night and after a restart it stopped working all of a sudden, second time this happens but first time I managed to get it sorted by just fully remove everything and just install it again, but since its a reoccurring problem I might aswell notify you.

To explain the problem at hand, it works fine and all it even notifying me that there is a new trade.
BUT!
The buttons don't seem to work properly, basically the problem is when you click the + it doesn't invite people, you can't click the chat icon nor the ? to see if they still want the item neither can you kick people with the - but it does automatically close the notification since I have that enabled.
Also the predefined messages that I have do not send, so I am assuming there is some trouble for your app to open the chat. (**_I DID NOT CHANGE ANY INGAME SETTINGS AND IT WORKED EARLIER_**)

Thank you in advance and thank you for an awesome app.
Netey

**Comment by etofok** [comment]
Don't run PoE as admin. If that didn't help use alternative launcher (run it as admin!). Keep in mind Steam by default runs PoE as admin, so you'll most likely need the alternative launcher to compensate (DON'T FORGET TO RUN THE .EXE AS ADMIN).

https://github.com/Exslims/MercuryTrade/releases

**Comment by tbarusseau** [comment]
Hello,

I'm having the exact same issue.
Running Windows 10, with disabled updates so it hasn't changed in a while.
Everything was working fine (incredible software, thanks a lot for it btw), and now it seems like it's active, but doesn't display on top of the Path of Exile window. Well, sometimes it does. But 95% of the time it doesn't. Which is weird, considering nothing seems to have changed?

I'm running the game in Windowed Fullscreen (which was already the case before), and I don't know what other game settings could be useful to you.

Is there some log I could give back to you, or any details that I could give to help solve this issue?

**Edit: just found out about the app.log. Well, the app seems to be working for now but I'll update with app.log in case it stops working.**

**Comment by Exslims** [comment]
if the problem still exists, please inform us about it

**Comment by Atlantisarch** [comment]
I had this kind of issue recently. My PC had some crash/BSOD I guess. I tried everything recommanded on the FAQ/topics about this matter, unsuccesfully. Only after hard rebooting mercurytrade (erasing whole parameters) AND desintalling/reinstalling java did I manage it make it working again. I guess the latest is THE thing my computer needed. Java, by not managing memory, is still crap ground to build on.
