### ISSUE TITLE
starting jar file frozes  operational system for few seconds

### ISSUE THREAD

**Issue by zbytt** [Exslims/MercuryTrade#70]
When i'm trying to start program, by dbl clicking the jar file, my operational system is "frozen" (music stops to play, cursor stucks in one place and so on) until MarcuryTrade starts, then everything is fine again

 I'm using Windows7

**Comment by Exslims** [comment]
I think it's a local problem, very low pc spec or something else.

**Comment by zbytt** [comment]
8GB of RAM, SSD Disk, i7-360QM processor, Windows7 64-bit

**Comment by Exslims** [comment]
i dunno what could be the problem, no one never asked, mb it is your local problem with java platform.
