### ISSUE TITLE
Can't launch mercury

### ISSUE THREAD

**Issue by DjaeCG** [Exslims/MercuryTrade#71]
When i try to launch it,it stays on the round blue thing and nothing else happens,i have to kill the app to make it disappear

**Comment by Exslims** [comment]
provide please app.log file from %userprofile%/appdata/local/mercurytrade folder

**Comment by DjaeCG** [comment]
The app log is empty

**Comment by Exslims** [comment]
@DjaeCG look at https://github.com/Exslims/MercuryTrade/issues/24 please.

**Comment by DjaeCG** [comment]
Ah,it was the problem,i've uninstalled Filebot and now it works find,thank you sir
