### ISSUE TITLE
Problem with invite on new launch.

### ISSUE THREAD

**Issue by sclient** [Exslims/MercuryTrade#73]
not sure if this is bc of something I changed, but when I click the inv button after a crash and relaunch, it doesnt use the right text string..

**Comment by Exslims** [comment]
provide pls app.log file from %userprofile%/appdata/local/MercuryTrade folder

**Comment by mrouija** [comment]
I've been having similar issues, attached is my app.log

Random buttons don't work, but I might need the EXE version now... Going to try that.  Just recently switched to Steam version again... =/

[app.log.txt](https://github.com/Exslims/MercuryTrade/files/911696/app.log.txt)

**Comment by sclient** [comment]
https://hastebin.com/yosezexohi.hs
Im pretty sure its a simple typo in the invite command..

**Comment by Exslims** [comment]
@sclient what is written in chat?

**Comment by Exslims** [comment]
if the problem still exists, please inform us about it
