### ISSUE TITLE
Ticket example

### ISSUE THREAD

**Issue by Exslims** [Exslims/MercuryTrade#74]
- Describe the problem
- Provide app.log file from %userprofile%/appdata/local/MercuryTrade folder.

**Comment by orgq3masch** [comment]
Problem concerns the new **Overseer** functionality.

Upon making **2 icons** for flasks I found the following problem:

When you press a button down (1) then press another button down (2) then release the first button (1) and then the second button (2) - the second icon timer starts, as it should, but the first one doesn't.
As I understand it the trigger for the icon timer starts upon _a release of a button_. Apparently pressing another one before releasing the first deletes it.
