### ISSUE TITLE
Issues with buttons

### ISSUE THREAD

**Issue by mrouija** [Exslims/MercuryTrade#75]
I've tried using Steam and Non-Steam POE launchers, as well as using the JAR and EXE (as admin) versions of Mercury Trade, and I get the same issue with all configurations.  Basically, I have to press buttons multiple times (5+) before a message/invite/trade request gets sent.  I had no issues with buttons prior to the latest update to Mercury Trade, and have since re-downloaded both JAR/EXE versions from the Github and all the issues remain.  I also get an error about update server being offline whenever I check for updates.  Lastly, my app.log hasn't been updated since the 8th of April, even though I use the software daily and have restarted several times.  I'm running Win 10 Pro, if that makes any difference.

**Comment by Exslims** [comment]
I hope in next update this problem will disappear.
