### ISSUE TITLE
Task bar keeps popping up

### ISSUE THREAD

**Issue by Nauze** [Exslims/MercuryTrade#77]
So, whenever the mercurytrade macro is on, my taskbar keeps popping up and it gets in the way of the screen, and i have to alt +tab twice to make it go back behind the game screen. Is there a reason it does this and is there a way to make it stop, its freaking annoying and already got me killed twice cuz this shit happened inside of breaches and bosses.

**Comment by Exslims** [comment]
Problem: Path of Exile constantly loses focus / Windows taskbar springs on top of the game while Mercury is running.

Fix: Disable Windows wallpaper slideshow.

**Comment by Exslims** [comment]
if the problem still exists, please inform us about it
