### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by thebeast792** [Exslims/MercuryTrade#8]
1. The history should be ordered so that the most recent trades are at the top so you don't need to scroll down every time you want to check your most recent trades. May even want some sorting option on there like a sort by asc or desc order button.
2. You should be able to click an "x" or close button to clear an individual entry in the history (and maybe a clear all button?).
3.  There should be a "trade made" option that will say a message like "thanks", kick the person from the party, and record the trade as completed in the history.  And also a "trade not made" option that will just kick the person from the part and record the trade as not followed in the history since the trade was not made.
4.  There should be a grand total of currency made from the trades in the history window (maybe on a bottom bar of the history window).

**Comment by Exslims** [comment]
Thanks for the suggestions, we will consider them and think about how they should be implemented.

**Comment by Exslims** [comment]
Even though I'd be awesome, we can't give you guys "respond ("thx") -> kick -> dismiss" as a single click because this is a blantant TOS violationm, but the other suggestions will be added if 3.0 will allow this)
