### ISSUE TITLE
getting 400 warnings

### ISSUE THREAD

**Issue by zaafar** [Exslims/MercuryTrade#80]
Hi,

I am new to Java ( from c++, C# background ). and while compiling MercuryTrade I am getting 400 warnings ([screenshot](https://ibb.co/c8AHak)). I am sure I am doing something wrong. Is it normal?

Let me know how to fix this. I am using java 8.

Thanks.

**Comment by Exslims** [comment]
looks like you need setup your Eclipse? for java 8(I recommend to use IntelliJ)

**Comment by zaafar** [comment]
I tried IntelliJ and it's compiling correctly but giving deprecated warning specially for [ConfigManager](https://github.com/Exslims/MercuryTrade/blob/master/app-core/src/main/java/com/mercury/platform/shared/ConfigManager.java#L25) but I see that this is removed in 3.0 so I am gonna close the issue.
Thx for the help. :)

**Comment by Exslims** [comment]
@zaafar Yes now it Deprecated, I'm slowly rewriting the configuration system in a more convenient system.
