### ISSUE TITLE
Stash Highlight

### ISSUE THREAD

**Issue by halexh** [Exslims/MercuryTrade#81]
Excuse me if I am missing something obvious, but the stash highlight does not seem to work for 4x4 tabs for me. I have activated the Item Grid option to align a grid with my stash tabs. I did it for each tab. 4 of my tabs are 1x1 tabs and one tab is a 4x4 tab. For each tab, I did grid align, selected the corresponding tab type (1x1 vs 4x4), and clicked save. Any stash highlight for 4x4 tabs seems to think its operating as a 1x1 tab.

After saving a 1x1 tab as 1v1 via grid align, I then go to the 4x4 tab and open grid align. For some reason it will default to 1v1, even though I had already set it to 4x4. The opposite scenario is not true. If I go from 4x4 tab after saving grid align as 4x4 for that tab to a 1x1 tab, opening grid align will default to 1v1. I may be doing way too much. If more information is needed please ask. I am probably just overlooking something obvious. Thanks!

**Comment by Exslims** [comment]
hm, names of tabs should be different.

**Comment by halexh** [comment]
They all are different names

**Comment by Exslims** [comment]
did you try restart mercury? there is a small bug with it issue

**Comment by halexh** [comment]
That fixed it - I see more options available now. I should have known better. Thanks!
