### ISSUE TITLE
Idea: Trade guard

### ISSUE THREAD

**Issue by thebeast792** [Exslims/MercuryTrade#83]
Just thought of an idea that should be possible to implement but hopefully not too difficult. Have MercuryTrade scan the trade window and see if each person has the correct currency/items in the trade window. It can try to read the person's name to see which trade offer is currently happening to compare against.

**Comment by Exslims** [comment]
Yes, there are already some ideas but now releasing updates is not very desirable), closer to the release 3.0 will be many updates
