### ISSUE TITLE
Wrong value used in Advanced Search

### ISSUE THREAD

**Issue by Genzzry** [Exslims/MercuryTrade#87]
Wrong value used in Advanced Search for "Chance to Block Spells"
For some reason, it used the value from "Chance to Block" instead of "Chance to Block Spells"

This is with the item Rearguard.
I am unsure if it also happens with other items.

Image attached.
No errors in log file for the past week or two, so didn't attach log.
  ##![wrongvalue](https://cloud.githubusercontent.com/assets/24488589/26299973/a95ccee8-3ed4-11e7-8cc6-888808303004.jpg)

**Comment by Exslims** [comment]
its a [Poe Trade Macro](https://github.com/PoE-TradeMacro/POE-TradeMacro), not MercuryTrade :) @Eruyome can you help him?

**Comment by Eruyome** [comment]
Oh, just have seen this now. I will look into it.

**Comment by Eruyome** [comment]
Just for the record, this is fixed in future releases.

**Comment by Genzzry** [comment]
Sorry for posting the bug to the wrong applications' bug thread.  I should have checked the icon :/

Thanks for passing this is on, Exslims... and thanks to Eruyome for fixing it!

You have both made great tools for the community.  I wish that I had found them sooner :)

**Comment by Exslims** [comment]
@Genzzry glad to hear it)
