### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by Dummynator** [Exslims/MercuryTrade#91]
Hi, i keep getting this error since about 2 -3 weeks 

> #
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffa33a7fd0c, pid=4660, tid=0x000000000000295c
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [d3d9.dll+0xfd0c]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x0000020903ca9000):  JavaThread "AWT-Windows" daemon [_thread_in_native, id=10588, stack(0x000000ec6a840000,0x000000ec6ad10000)]

siginfo: ExceptionCode=0xc0000005, writing address 0x0000000000000000

Registers:
RAX=0x0000000000000000, RBX=0x000000ec6ad0dec0, RCX=0x0000020906e3d400, RDX=0x000000ec6ad0e6d0
RSP=0x000000ec6ad0de18, RBP=0x000000ec6ad0e1b0, RSI=0x0000000000000001, RDI=0x0000020906e37780
R8 =0x0000000000000000, R9 =0x0000000000000000, R10=0x0000020906e3e21c, R11=0x0000000000000246
R12=0x0000000000000001, R13=0x000000ec6ad0e6d0, R14=0x0000000000000000, R15=0x0000000000000000
RIP=0x00007ffa33a7fd0c, EFLAGS=0x0000000000010246

Top of Stack: (sp=0x000000ec6ad0de18)
0x000000ec6ad0de18:   00007ffa33a8167f 000000ec6ad0de78
0x000000ec6ad0de28:   000000ec6ad0de80 0000000000000880
0x000000ec6ad0de38:   0000000000010001 0000020900000000
0x000000ec6ad0de48:   0000020906e37780 0000000000000000
0x000000ec6ad0de58:   00007ffa33a976a6 0000020900000000
0x000000ec6ad0de68:   0000000000000000 0000000000000001
0x000000ec6ad0de78:   0000000000000001 0000020900000000
0x000000ec6ad0de88:   0000000000000000 0000000000005c88
0x000000ec6ad0de98:   0000000000005c90 0000000000000000
0x000000ec6ad0dea8:   000000ec6ad0def8 0000020900000000
0x000000ec6ad0deb8:   000000000000001a 0000000000000000
0x000000ec6ad0dec8:   0000000000000000 000002096e752ae0
0x000000ec6ad0ded8:   0000020906e3d400 0000000000000000
0x000000ec6ad0dee8:   000002096e73a8f8 0000000000000000
0x000000ec6ad0def8:   000000ec00000003 0000000000000000
0x000000ec6ad0df08:   0000000000000000 0000000000000048 

Instructions: (pc=0x00007ffa33a7fd0c)
0x00007ffa33a7fcec:   e9 10 fe ff ff cc cc cc cc cc cc cc cc cc cc cc
0x00007ffa33a7fcfc:   cc cc cc cc ff 25 00 00 00 00 30 96 01 80 01 00
0x00007ffa33a7fd0c:   00 00 5c 24 20 55 56 57 41 54 41 55 41 56 41 57
0x00007ffa33a7fd1c:   48 8d 6c 24 c0 48 81 ec 40 01 00 00 48 8b 05 a9 

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX=0x000000ec6ad0dec0 is pointing into the stack for thread: 0x0000020903ca9000
RCX=0x0000020906e3d400 is an unknown value
RDX=0x000000ec6ad0e6d0 is pointing into the stack for thread: 0x0000020903ca9000
RSP=0x000000ec6ad0de18 is pointing into the stack for thread: 0x0000020903ca9000
RBP=0x000000ec6ad0e1b0 is pointing into the stack for thread: 0x0000020903ca9000
RSI=0x0000000000000001 is an unknown value
RDI=0x0000020906e37780 is an unknown value
R8 =0x0000000000000000 is an unknown value
R9 =0x0000000000000000 is an unknown value
R10=0x0000020906e3e21c is an unknown value
R11=0x0000000000000246 is an unknown value
R12=0x0000000000000001 is an unknown value
R13=0x000000ec6ad0e6d0 is pointing into the stack for thread: 0x0000020903ca9000
R14=0x0000000000000000 is an unknown value
R15=0x0000000000000000 is an unknown value

Stack: [0x000000ec6a840000,0x000000ec6ad10000],  sp=0x000000ec6ad0de18,  free space=4919k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [d3d9.dll+0xfd0c]
C  [d3d9.dll+0x1167f]
C  [d3d9.dll+0x276a6]
C  [d3d9.dll+0x2cb68]
C  [d3d9.dll+0x2a81e]
C  [awt.dll+0x19e3d]
C  [awt.dll+0x19f9b]
C  [awt.dll+0x1a94f]
C  [awt.dll+0x1e505]
C  [awt.dll+0x1b619]
C  0x000002097017925b

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  sun.java2d.d3d.D3DGraphicsDevice.getDeviceCapsNative(I)I+0
j  sun.java2d.d3d.D3DGraphicsDevice.access$000(I)I+1
j  sun.java2d.d3d.D3DGraphicsDevice$1.run()V+8
v  ~StubRoutines::call_stub
j  sun.awt.windows.WToolkit.eventLoop()V+0
j  sun.awt.windows.WToolkit.run()V+58
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
=>0x0000020903ca9000 JavaThread "AWT-Windows" daemon [_thread_in_native, id=10588, stack(0x000000ec6a840000,0x000000ec6ad10000)]
  0x0000020903ca4000 JavaThread "AWT-Shutdown" [_thread_blocked, id=10232, stack(0x000000ec6a370000,0x000000ec6a840000)]
  0x0000020903ca3800 JavaThread "Java2D Disposer" daemon [_thread_blocked, id=12996, stack(0x000000ec69ea0000,0x000000ec6a370000)]
  0x00000209035f8800 JavaThread "Service Thread" daemon [_thread_blocked, id=2840, stack(0x000000ec69500000,0x000000ec699d0000)]
  0x000002097fc35800 JavaThread "C1 CompilerThread2" daemon [_thread_blocked, id=5104, stack(0x000000ec69030000,0x000000ec69500000)]
  0x000002097fc32800 JavaThread "C2 CompilerThread1" daemon [_thread_blocked, id=7368, stack(0x000000ec68b60000,0x000000ec69030000)]
  0x000002097fc30000 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=708, stack(0x000000ec68690000,0x000000ec68b60000)]
  0x000002097fc2e800 JavaThread "Attach Listener" daemon [_thread_blocked, id=4704, stack(0x000000ec681c0000,0x000000ec68690000)]
  0x000002097fc2d800 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=10856, stack(0x000000ec67cf0000,0x000000ec681c0000)]
  0x000002097015b800 JavaThread "Finalizer" daemon [_thread_blocked, id=4908, stack(0x000000ec67820000,0x000000ec67cf0000)]
  0x0000020970152800 JavaThread "Reference Handler" daemon [_thread_blocked, id=8948, stack(0x000000ec67350000,0x000000ec67820000)]
  0x000002096e6ae800 JavaThread "main" [_thread_in_native, id=12924, stack(0x000000ec64800000,0x000000ec64cd0000)]

Other Threads:
  0x000002097fbf7800 VMThread [stack: 0x000000ec66e80000,0x000000ec67350000] [id=10592]
  0x000002090361b000 WatcherThread [stack: 0x000000ec699d0000,0x000000ec69ea0000] [id=11536]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap:
 PSYoungGen      total 76288K, used 27631K [0x00000000eab00000, 0x00000000f0000000, 0x0000000100000000)
  eden space 65536K, 42% used [0x00000000eab00000,0x00000000ec5fbef8,0x00000000eeb00000)
  from space 10752K, 0% used [0x00000000ef580000,0x00000000ef580000,0x00000000f0000000)
  to   space 10752K, 0% used [0x00000000eeb00000,0x00000000eeb00000,0x00000000ef580000)
 ParOldGen       total 175104K, used 0K [0x00000000c0000000, 0x00000000cab00000, 0x00000000eab00000)
  object space 175104K, 0% used [0x00000000c0000000,0x00000000c0000000,0x00000000cab00000)
 Metaspace       used 12798K, capacity 12958K, committed 13312K, reserved 1060864K
  class space    used 1619K, capacity 1666K, committed 1792K, reserved 1048576K

Card table byte_map: [0x000002097f520000,0x000002097f730000] byte_map_base: 0x000002097ef20000

Marking Bits: (ParMarkBitMap*) 0x000000006cc3b6d0
 Begin Bits: [0x0000020900000000, 0x0000020901000000)
 End Bits:   [0x0000020901000000, 0x0000020902000000)

Polling page: 0x000002096e640000

CodeCache: size=245760Kb used=3091Kb max_used=3091Kb free=242668Kb
 bounds [0x0000020970160000, 0x0000020970470000, 0x000002097f160000]
 total_blobs=1234 nmethods=823 adapters=324
 compilation: enabled

Compilation events (10 events):
Event: 0.390 Thread 0x000002097fc35800  818       3       java.util.Vector::elementData (7 bytes)
Event: 0.390 Thread 0x000002097fc35800 nmethod 818 0x0000020970463e10 code [0x0000020970463f60, 0x00000209704640d8]
Event: 0.393 Thread 0x000002097fc35800  819       3       jdk.internal.org.objectweb.asm.ByteVector::enlarge (51 bytes)
Event: 0.393 Thread 0x000002097fc35800 nmethod 819 0x00000209704641d0 code [0x0000020970464340, 0x0000020970464670]
Event: 0.394 Thread 0x000002097fc35800  820       1       java.lang.invoke.MethodTypeForm::basicType (5 bytes)
Event: 0.394 Thread 0x000002097fc35800 nmethod 820 0x0000020970464750 code [0x00000209704648a0, 0x00000209704649b8]
Event: 0.417 Thread 0x000002097fc35800  822       3       jdk.internal.org.objectweb.asm.ClassWriter::put122 (15 bytes)
Event: 0.417 Thread 0x000002097fc35800 nmethod 822 0x0000020970464b90 code [0x0000020970464d00, 0x0000020970464f00]
Event: 0.417 Thread 0x000002097fc35800  823  s    3       java.util.Vector::elementAt (48 bytes)
Event: 0.417 Thread 0x000002097fc35800 nmethod 823 0x0000020970465010 code [0x0000020970465220, 0x0000020970465dd0]

GC Heap History (0 events):
No events

Deoptimization events (7 events):
Event: 0.269 Thread 0x000002096e6ae800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x000002097036b090 method=sun.misc.MetaIndex.mayContain(Ljava/lang/String;)Z @ 38
Event: 0.269 Thread 0x000002096e6ae800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00000209703111f0 method=sun.misc.MetaIndex.mayContain(Ljava/lang/String;)Z @ 38
Event: 0.281 Thread 0x000002096e6ae800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x0000020970384008 method=java.util.HashMap.getNode(ILjava/lang/Object;)Ljava/util/HashMap$Node; @ 129
Event: 0.281 Thread 0x000002096e6ae800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x000002097036433c method=java.util.HashMap.getNode(ILjava/lang/Object;)Ljava/util/HashMap$Node; @ 129
Event: 0.282 Thread 0x000002096e6ae800 Uncommon trap: reason=range_check action=make_not_entrant pc=0x000002097033f420 method=sun.reflect.generics.parser.SignatureParser.current()C @ 34
Event: 0.315 Thread 0x000002096e6ae800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00000209702d9980 method=java.lang.String.indexOf([CII[CIII)I @ 3
Event: 0.349 Thread 0x000002096e6ae800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x0000020970365478 method=sun.net.www.ParseUtil.encodePath(Ljava/lang/String;Z)Ljava/lang/String; @ 109

Internal exceptions (10 events):
Event: 0.064 Thread 0x000002096e6ae800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000ead9f9f0) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u121\8372\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.064 Thread 0x000002096e6ae800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000ead9fc00) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u121\8372\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.065 Thread 0x000002096e6ae800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000eada3e28) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u121\8372\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.065 Thread 0x000002096e6ae800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000eada4038) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u121\8372\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.282 Thread 0x000002096e6ae800 Exception <a 'java/lang/ArrayIndexOutOfBoundsException': 18> (0x00000000ebd154a0) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u121\8372\hotspot\src\share\vm\interpreter\interpreterRuntime.cpp, line 366]
Event: 0.282 Thread 0x000002096e6ae800 Exception <a 'java/lang/ArrayIndexOutOfBoundsException': 110> (0x00000000ebd169f8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u121\8372\hotspot\src\share\vm\interpreter\interpreterRuntime.cpp, line 366]
Event: 0.353 Thread 0x000002096e6ae800 Exception <a 'java/io/FileNotFoundException'> (0x00000000ec1f8a60) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u121\8372\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 0.368 Thread 0x000002096e6ae800 Exception <a 'java/lang/NoSuchFieldError': method resolution failed> (0x00000000ec2c0e50) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u121\8372\hotspot\src\share\vm\prims\methodHandles.cpp, line 1146]
Event: 0.368 Thread 0x000002096e6ae800 Exception <a 'java/lang/NoSuchFieldError': method resolution failed> (0x00000000ec2ce140) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u121\8372\hotspot\src\share\vm\prims\methodHandles.cpp, line 1146]
Event: 0.390 Thread 0x000002096e6ae800 Exception <a 'java/io/FileNotFoundException'> (0x00000000ec377360) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u121\8372\hotspot\src\share\vm\prims\jni.cpp, line 709]

Events (10 events):
Event: 0.427 loading class sun/java2d/pipe/RenderQueue done
Event: 0.427 loading class sun/java2d/d3d/D3DRenderQueue done
Event: 0.427 loading class sun/java2d/pipe/RenderBuffer
Event: 0.427 loading class sun/java2d/pipe/RenderBuffer done
Event: 0.427 loading class sun/java2d/d3d/D3DRenderQueue$1
Event: 0.427 loading class sun/java2d/d3d/D3DRenderQueue$1 done
Event: 0.427 loading class sun/java2d/d3d/D3DGraphicsDevice$1Result
Event: 0.427 loading class sun/java2d/d3d/D3DGraphicsDevice$1Result done
Event: 0.427 loading class sun/java2d/d3d/D3DGraphicsDevice$1
Event: 0.427 loading class sun/java2d/d3d/D3DGraphicsDevice$1 done

Dynamic libraries:
0x00007ff62ac40000 - 0x00007ff62ac89000 	C:\Users\Big Frank\Desktop\MercuryTrade\MercuryTrade.exe
0x00007ffa595e0000 - 0x00007ffa597bb000 	C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ffa56fd0000 - 0x00007ffa5707e000 	C:\WINDOWS\System32\KERNEL32.DLL
0x00007ffa56660000 - 0x00007ffa568a9000 	C:\WINDOWS\System32\KERNELBASE.dll
0x00007ffa54020000 - 0x00007ffa5409e000 	C:\WINDOWS\SYSTEM32\apphelp.dll
0x000000006c420000 - 0x000000006ccbb000 	C:\Users\Big Frank\Desktop\MercuryTrade\jre\bin\server\jvm.dll
0x00007ffa57080000 - 0x00007ffa571ca000 	C:\WINDOWS\System32\USER32.dll
0x00007ffa56910000 - 0x00007ffa5692e000 	C:\WINDOWS\System32\win32u.dll
0x00007ffa58e00000 - 0x00007ffa58e27000 	C:\WINDOWS\System32\GDI32.dll
0x00007ffa55c00000 - 0x00007ffa55d88000 	C:\WINDOWS\System32\gdi32full.dll
0x00007ffa56930000 - 0x00007ffa569ca000 	C:\WINDOWS\System32\msvcp_win.dll
0x00007ffa55b00000 - 0x00007ffa55bf6000 	C:\WINDOWS\System32\ucrtbase.dll
0x00007ffa590e0000 - 0x00007ffa59181000 	C:\WINDOWS\System32\ADVAPI32.dll
0x00007ffa58d60000 - 0x00007ffa58dfd000 	C:\WINDOWS\System32\msvcrt.dll
0x00007ffa59190000 - 0x00007ffa591e9000 	C:\WINDOWS\System32\sechost.dll
0x00007ffa59250000 - 0x00007ffa59375000 	C:\WINDOWS\System32\RPCRT4.dll
0x00007ffa595d0000 - 0x00007ffa595d8000 	C:\WINDOWS\System32\PSAPI.DLL
0x00007ffa45ef0000 - 0x00007ffa45f13000 	C:\WINDOWS\SYSTEM32\WINMM.dll
0x00007ffa523e0000 - 0x00007ffa523ea000 	C:\WINDOWS\SYSTEM32\VERSION.dll
0x00007ffa38b80000 - 0x00007ffa38b89000 	C:\WINDOWS\SYSTEM32\WSOCK32.dll
0x000000006c340000 - 0x000000006c411000 	C:\WINDOWS\SYSTEM32\MSVCR100.dll
0x00007ffa45ec0000 - 0x00007ffa45eeb000 	C:\WINDOWS\SYSTEM32\WINMMBASE.dll
0x00007ffa572a0000 - 0x00007ffa5730c000 	C:\WINDOWS\System32\WS2_32.dll
0x00007ffa56af0000 - 0x00007ffa56b39000 	C:\WINDOWS\System32\cfgmgr32.dll
0x00007ffa56fa0000 - 0x00007ffa56fcd000 	C:\WINDOWS\System32\IMM32.DLL
0x000000006c330000 - 0x000000006c33f000 	C:\Users\Big Frank\Desktop\MercuryTrade\jre\bin\verify.dll
0x000000006c300000 - 0x000000006c329000 	C:\Users\Big Frank\Desktop\MercuryTrade\jre\bin\java.dll
0x000000006c2e0000 - 0x000000006c2f6000 	C:\Users\Big Frank\Desktop\MercuryTrade\jre\bin\zip.dll
0x00007ffa57770000 - 0x00007ffa58ba7000 	C:\WINDOWS\System32\SHELL32.dll
0x00007ffa571d0000 - 0x00007ffa5727a000 	C:\WINDOWS\System32\shcore.dll
0x00007ffa57310000 - 0x00007ffa57609000 	C:\WINDOWS\System32\combase.dll
0x00007ffa569d0000 - 0x00007ffa56a3a000 	C:\WINDOWS\System32\bcryptPrimitives.dll
0x00007ffa55d90000 - 0x00007ffa56482000 	C:\WINDOWS\System32\windows.storage.dll
0x00007ffa591f0000 - 0x00007ffa59241000 	C:\WINDOWS\System32\shlwapi.dll
0x00007ffa55ae0000 - 0x00007ffa55af1000 	C:\WINDOWS\System32\kernel.appcore.dll
0x00007ffa55a50000 - 0x00007ffa55a9c000 	C:\WINDOWS\System32\powrprof.dll
0x00007ffa55aa0000 - 0x00007ffa55ab5000 	C:\WINDOWS\System32\profapi.dll
0x000000006c2d0000 - 0x000000006c2dd000 	C:\Users\Big Frank\Desktop\MercuryTrade\jre\bin\management.dll
0x000000006c2b0000 - 0x000000006c2ca000 	C:\Users\Big Frank\Desktop\MercuryTrade\jre\bin\net.dll
0x00007ffa55360000 - 0x00007ffa553bc000 	C:\WINDOWS\system32\mswsock.dll
0x00007ffa37b90000 - 0x00007ffa37ba6000 	C:\WINDOWS\system32\napinsp.dll
0x00007ffa37b70000 - 0x00007ffa37b8a000 	C:\WINDOWS\system32\pnrpnsp.dll
0x00007ffa52490000 - 0x00007ffa524a8000 	C:\WINDOWS\system32\NLAapi.dll
0x00007ffa55140000 - 0x00007ffa551e4000 	C:\WINDOWS\SYSTEM32\DNSAPI.dll
0x00007ffa56f90000 - 0x00007ffa56f98000 	C:\WINDOWS\System32\NSI.dll
0x00007ffa55100000 - 0x00007ffa55137000 	C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
0x00007ffa3c260000 - 0x00007ffa3c26e000 	C:\WINDOWS\System32\winrnr.dll
0x00007ffa40da0000 - 0x00007ffa40daa000 	C:\Windows\System32\rasadhlp.dll
0x00007ffa46880000 - 0x00007ffa468eb000 	C:\WINDOWS\System32\fwpuclnt.dll
0x00007ffa55610000 - 0x00007ffa55635000 	C:\WINDOWS\SYSTEM32\bcrypt.dll
0x000000006c290000 - 0x000000006c2a1000 	C:\Users\Big Frank\Desktop\MercuryTrade\jre\bin\nio.dll
0x000000006c0f0000 - 0x000000006c288000 	C:\Users\Big Frank\Desktop\MercuryTrade\jre\bin\awt.dll
0x00007ffa57610000 - 0x00007ffa576d0000 	C:\WINDOWS\System32\OLEAUT32.dll
0x00007ffa525f0000 - 0x00007ffa5261a000 	C:\WINDOWS\system32\DWMAPI.DLL
0x00007ffa541b0000 - 0x00007ffa54245000 	C:\WINDOWS\system32\uxtheme.dll
0x00007ffa1b2c0000 - 0x00007ffa1b3e1000 	C:\WINDOWS\system32\opengl32.dll
0x00007ffa32e00000 - 0x00007ffa32e2c000 	C:\WINDOWS\SYSTEM32\GLU32.dll
0x00007ffa40b40000 - 0x00007ffa40be6000 	C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.15063.413_none_0e0f5dcc67adff4e\COMCTL32.dll
0x00007ffa59400000 - 0x00007ffa59566000 	C:\WINDOWS\System32\MSCTF.dll
0x0000000180000000 - 0x0000000180037000 	C:\Program Files (x86)\RivaTuner Statistics Server\RTSSHooks64.dll
0x000000006f380000 - 0x000000006f423000 	C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9279_none_08e667efa83ba076\MSVCR90.dll
0x00007ffa58c10000 - 0x00007ffa58d55000 	C:\WINDOWS\System32\ole32.dll
0x00007ffa33a70000 - 0x00007ffa33bf9000 	C:\WINDOWS\system32\d3d9.dll
0x00007ffa3da60000 - 0x00007ffa3dbf6000 	C:\WINDOWS\System32\DriverStore\FileRepository\c0314971.inf_amd64_2415907414930af2\aticfx64.dll
0x00007ffa33a30000 - 0x00007ffa33a62000 	C:\WINDOWS\System32\DriverStore\FileRepository\c0314971.inf_amd64_2415907414930af2\atiu9p64.dll
0x00007ffa330f0000 - 0x00007ffa33a26000 	C:\WINDOWS\System32\DriverStore\FileRepository\c0314971.inf_amd64_2415907414930af2\atiumd64.dll
0x0000000070320000 - 0x0000000071147000 	C:\WINDOWS\System32\DriverStore\FileRepository\c0314971.inf_amd64_2415907414930af2\atiumd6a.dll
0x00007ffa3cdc0000 - 0x00007ffa3cde5000 	C:\WINDOWS\SYSTEM32\amdihk64.dll
0x000000000f000000 - 0x000000000f006000 	C:\WINDOWS\SYSTEM32\detoured.dll
0x00007ffa52040000 - 0x00007ffa521e9000 	C:\WINDOWS\SYSTEM32\dbghelp.dll

VM Arguments:
jvm_args: -Xmx1G 
java_command: <unknown>
java_class_path (initial): <not set>
Launcher Type: generic

Environment Variables:
PATH=C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Users\Big Frank\AppData\Local\Microsoft\WindowsApps
USERNAME=Big Frank
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 9, GenuineIntel

---------------  S Y S T E M  ---------------

OS: Windows 10.0 , 64 bit Build 15063 (10.0.15063.296)

CPU:total 4 (4 cores per cpu, 1 threads per core) family 6 model 158 stepping 9, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, erms, rtm, 3dnowpref, lzcnt, tsc, tscinvbit, bmi1, bmi2, adx

Memory: 4k page, physical 16737496k(11422528k free), swap 19752152k(8143504k free)

vm_info: Java HotSpot(TM) 64-Bit Server VM (25.121-b13) for windows-amd64 JRE (1.8.0_121-b13), built on Dec 12 2016 18:21:36 by "java_re" with MS VC++ 10.0 (VS2010)

time: Sat Jun 17 23:24:45 2017
elapsed time: 0 seconds (0d 0h 0m 0s)

>

**Comment by Exslims** [comment]
hi, that is, the program works but after closing the file appears this error?

**Comment by Dummynator** [comment]
no, the program just wont start at all. when i click on it a new .txt document error appears in the folder of mercury trade. i literally didnt change anything to my computer before that started hapenning (else than maybe a poe patch/hotfix, didnt notice). Thanks for answering!


________________________________
De : Konstantin <notifications@github.com>
Envoyé : 23 juin 2017 17:04
À : Exslims/MercuryTrade
Cc : Dummynator; Author
Objet : Re: [Exslims/MercuryTrade] Java error (#91)


hi, that is, the program works but after closing the file appears this error?

**Comment by Exslims** [comment]
can you delete your java and install latest version from [https://www.java.com/ru/download/win10.jsp](url)

**Comment by Dummynator** [comment]
Hi,


i did all that, tried updating my graphics card driver, still have the same problem.

________________________________
De : Konstantin <notifications@github.com>
Envoyé : 23 juin 2017 21:08
À : Exslims/MercuryTrade
Cc : Dummynator; Author
Objet : Re: [Exslims/MercuryTrade] Java error (#91)


can you delete your java and install latest version from https://www.java.com/ru/download/win10.jsp<url>

**Comment by Exslims** [comment]
Problem: Mercury don't want to run and creates many of crash report files.
Fix: Switch-off RivaTune app

**Comment by Dummynator** [comment]
Hi, thanks but i been running it with riva tuner without any problem whatsoever, why is there now?


________________________________
De : Konstantin <notifications@github.com>
Envoyé : 4 août 2017 13:23
À : Exslims/MercuryTrade
Cc : Dummynator; Author
Objet : Re: [Exslims/MercuryTrade] Java error (#91)


Problem: Mercury don't want to run and creates many of crash report files.
Fix: Switch-off RivaTune app(изменено)

**Comment by Exslims** [comment]
this problem appeared аfter windows creators update on win10
