### ISSUE TITLE
Installation error?

### ISSUE THREAD

**Issue by dchoi44** [Exslims/MercuryTrade#94]
After I run .jar file, I only get icon of the program (circular mark with navy blue-ish color) and nothing happens. 

I have my java version of 1.8.0_131.
Running .exe file with administrator gives the same result.

Thanks!

**Comment by Exslims** [comment]
hi, please provide app.log file from %userprofile%/appdata/local/mercurytrade folder

**Comment by dchoi44** [comment]
I am afraid, but there is no content in the file.. it's blank

**Comment by Exslims** [comment]
its looks like privileges problem, can you move MT to your root disc?

**Comment by Exslims** [comment]
or you have installed FileBot (unistall should help)
