### ISSUE TITLE
Mercury Trade changes my keyboard functionality with regard to special characters

### ISSUE THREAD

**Issue by AJvanLoon** [Exslims/MercuryTrade#99]
First of all, thanks for making such an awesome tool. I wouldn't want to trade without it anymore. Also, I am not sure whether this issue was already happening with older versions. I certainly don't remember it being a problem.

To my issue at hand:

Yesterday, I suddenly started having problems with typing special characters (', ", `, é, ë, è, etc.) and spent a few hours in frustration trying to fix it. As it turns out, Mercury Trade is/seems to be causing it. On my keyboard (using input language Dutch (Netherlands) - United States-International) special characters usually work as follows: when you first press the button for an apostrophe, for instance, nothing happens. Then you can press either the space bar for the apostrophe to show up, or press a vowel key to type letters such as à, ö, é.

Now, when I open MercuryTrade.jar (latest version), the functionality completely changes. The only way for me to type an apostrophe is by double pressing the key, after which two apostrophes show up and I then have to delete one. Typing letters such as é and ö becomes entirely impossible when the program is active. As soon as I close the program, everything immediately works as it should again.

While I have no idea what could be causing this, or even whether this is a result of Mercury in particular as opposed to Java in general, I wanted to bring it to your attention nonetheless. Now that I know that my keyboard settings aren't changing themselves through some type of dark magic, it's a minor annoyance at best, but still!

Is this intended behavior? Is it related to Overseer perhaps?

**Comment by Exslims** [comment]
this problem is related to hotkey buttons which were put together with overseer, thanks for detailed report, i will try to fix this.

**Comment by AJvanLoon** [comment]
Much obliged!

**Comment by jeffarese** [comment]
Happens to me as well :(

**Comment by ThiagoCururu** [comment]
I was about to rip my hair off out of despair because I couldn't figure out what was going on with my keyboard/windows/input... When I found out it was Mercury Trade I was relieved, but also sad, because this is an amazing tool! I also play a Pathfinder and that Overseer is amazing to keep my flasks up without setting up a macro.

Unfortunately it is too harsh for me to give up proper grammar, so until this is fixed, I'll be using POE Trades Companion by Iemasato. Switching back as soon as this is fixed. Thank you Exslims for this amazing tool!

**Comment by Exslims** [comment]
in next update mercury will use another library for keyboard hook and hope it will help to solve this problem.

**Comment by Exslims** [comment]
hope 1.0.1.7 solved this problem

**Comment by jeffarese** [comment]
Yep, it solved it for me 😄 👍

**Comment by AJvanLoon** [comment]
Fixed indeed. Thanks!

**Comment by ThiagoCururu** [comment]
Fixed and it was pretty fast. Thank you!
